---
collections:
  - name: community.docker
    version: 2.0.2
  - name: community.general
    version: 4.2.0
  - name: community.sops
    version: 1.2.0
  - name: ansible.posix
    version: 1.3.0
roles:
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.1.1
  - src: xanmanning.k3s
    version: v2.12.1
