---
collections:
  - name: community.docker
    version: 2.3.0
  - name: community.general
    version: 4.5.0
  - name: community.sops
    version: 1.2.1
  - name: ansible.posix
    version: 1.3.0
roles:
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.1.3
  - src: xanmanning.k3s
    version: v3.1.1
