# yamllint disable
# Use an existing secret for the admin user.
# admin:
#   existingSecret: ""
#   userKey: admin-user
#   passwordKey: admin-password
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:U7gKh9+tjg==,iv:NrGxY4C9gQ2E5lMImppRjpvwyGqYGHaoeR8xDKTzSpU=,tag:kD1UQVsvk2JnVvfZNCOxsw==,type:str]
    admin-password: ENC[AES256_GCM,data:oAw8ONtQMeDo3ia8,iv:FXS1CTJyeUWca7I0sPh42MBzZgEwWCrc2aLqBKXC0/M=,tag:Ch4gPgu9Bs3JtcAPSPR0gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-01T16:27:05Z"
    mac: ENC[AES256_GCM,data:yh40LVmFgrduu6kpYkILC7O30vvcbYDKa8dsWa0X0KeCCexE3Yoff9HKcUOKSI2dEb33kYbsaafscMA2f15B4SMUcOnKCVb32CEGjZ1hk2kzEmAEbQj9+KG2SrG0SeMUNF/osSVPqB9JowGMrL8IlrukWyWMsTt7WZb2qYsUf58=,iv:JoVW98nFrnlXrvyhy91VIaTRq+Ww4ftLZINxlnsmkqc=,tag:9VVp/Hmqk0HyIwB5mBynYw==,type:str]
    pgp:
        - created_at: "2021-12-01T16:27:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZARAAmeKr+odJnkgz77BzsLQjip3/pF9ScjbQQEp3ITN9nRjW
            M7cPoT72JCFLLpSHu5bCUpzMcf98i6tvrmbf0v8JD9/o1K8CiYyC7e2inGAcNumk
            ew6Q2/yAHvFiULWTRlqfma8cZHhcCYmONaRbhmCNQbCb/Jl2s7WyewGmAeegyJ2m
            ryjaRxoYYSp5wkxS2zmrgGTeyGw4aVJzghHPCK5/+hkt7QJfsAz5qloXU+uPkb62
            pcZ0BGBt3Tymmc3rC1/EN1icl8KPrxSPdUF04VH+ZaA7PmUj6/22gtx9WHigQqIA
            3i39g8iaJiZg+ZyAesaAABlJeLlY6+wRtlNupg+6iwYOQVTnvMmCoHvXZE6DQZt5
            dCVU1RpwlvYjcz2h/sgAWKZqhndXbm9Qrwn9UcS+bPlLcqRTnirtMK7kpaMSVQLR
            9yRT9veVTTrilLYupe9rGUKJimgKie+AAra/5X2lRGom1+KLtqrOC1VGMBqvlS0J
            uWpLnFPrRbivAOc61d7iewrb2uW3f+sOleUL5FSHoMxM7iswst3g+0tqUkeJBg9P
            XekHFme6TfydYntJywqv6/rkViFUcfIgh4w0rZf92VkmT3NU3KCGpUoI4w2pMddB
            798MHrH3J3QqVwQmk3J606Buu3ujvfZV6tqLCg7KZoWCuElgrW3723fzd8mjqNbS
            XAGBi8lS1fT/Ln1Gw5s0GfPfLTZNXh3khKPdJ1l2M0AwhLRsMHSd3vuKteZOW3Ug
            SLsu34/bZrLqEolGg+cNavpjQuXaX3sOIWwQhCz1uHwPHmBWRtD3QazF1gjB
            =Iien
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-12-01T16:27:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/+JjRfeI0Pb4aflGCIiQTQA0vXvMPI9U338hHDzUUCeS3S
            cmBXHzu7aIDUUkaZ6u5SMHLeinZVQ10zwVhVrEqI5KOhyQKAoMt0dm40c1k2I4Ci
            uibrHNNvjnhGNHdvO3o7c3dujcLyr6r6QSBfSxJ+fDZRSkasFxxVfArdn2ykGgU/
            zMh4V4GDRfss7FTZ3ePZr/bSsZJAFHKpkB5LQzM1hLAflC6B05UyeYpKPeG/RQV8
            cgtOCgbpxXq1uzLmBKLMdoTL31zUT5kNwMv7VdNc1Ie/J2mnhHFmVaz3S1zliVTL
            uyf3d5H3e5YehOBbd1d7IpWKl1YFihtZC0h+jALuHkS9Ju2Ai0KJOB/VpHoIpAQd
            aZ0K8Tj3ap+m0zq10fQLyRntWLGG/Kls485byVI9uJXdC7lTxIlQTz85iFcUh3hS
            +i3J79qvwPUvvrar/2GJEaQ28gUkdqpiembJXQ0JQSuX+3GeCcLa8/TOhrKMQdQU
            AyGNa3F8nQAJZ0XYCyLRvdbbBSNS2ARc3KWyzJEaVjrmztJUFhec7SBdnPSqTVj8
            7KoJAwAgSm7Rrhn7Uv6RbQz6N3dR9YRJT2RMxKPVx3uM+drPdNuvYE9iBThSFBx+
            5rpVyrxEtBR8IahXG0GCGo/Sv7ktxqjcln0flkDaUVT4KCFGnrQ/mExo4AHCxc7S
            XAEbl9geFBXGhFZpzqwO7IxZpLj/Mut1HHlzTr0xKwNEDXS4zQaEkWJHFUHalGn5
            n7qSktePTf+5cwCptZHEnLDLH+jnEWe1Ggq2kmdVEFF8DKxsAVtEkHRV8vyj
            =64Qv
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
