# yamllint disable
# Use an existing secret for the admin user.
# admin:
#   existingSecret: ""
#   userKey: admin-user
#   passwordKey: admin-password
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:WTydJs6WcQ==,iv:wHRpS/GVmuaSLTgSOGizcrmpV7pe7O2F2DVTxMYP/oY=,tag:seRe/2528Ea37cUPhCy2aQ==,type:str]
    admin-password: ENC[AES256_GCM,data:xNcpvhGMPLZ31sgc,iv:RiJ8BM2W/TbTeIZBnGYeZrFCvnqss/tmhs2CK8v66o0=,tag:do5SAhEzmfBbL6ZJew+MXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOTN1S29Fdy9hQ0FWbWRV
            Z3V3VFFZdExKNVpDMHJXK0FnalYrOGRoR0JJCmNRbzBGN3JEeHlWQ0pJNTVzYlEw
            YitaSHdOVDJVRnZ6V0lWd2xNVkg0TEUKLS0tIEwvRWVLSCtBcHo0c1pXSjA3a3k0
            bGdHK2hLT1RaMytOYXlSR1RMYlVia1kK1l+CTvNQ2Sqd7FH/Lc/nLIxTu/kDfoaC
            qHA7gQhti1Kv+vPMdodNS/vzJe1nREdRX0kYbkhDN9MLEBeyHcOXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:1rQ4S7XhqCoj7Q80/9p5EqEjEFp433tD+uPsVu3pG/iCnl6Bq0KNoWME+TKFwzPATYwrLjoVqfbbsilqgwUgbyik3dU8LqbcTL1JsbajV1PyRO1U8x0gI9S6SDezwlXVpfN0gxF/mvmQQRODjfpSadshe1PDhDgAUsX8LN4/RXI=,iv:iwnNHAh6u654+gk0jGczpv3zCA5+NJnVuayn5aRtQ/k=,tag:WbzGiELRkTND5tKiNQTooA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
