apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - cloudflare-ddns
  - external-dns
  - traefik
  - traefik-public
  - unifi-controller
  - wildcard-certificate
