---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  # TODO: Troubleshoot the MountVolume failure that continues to happen
  # - cloudflare-ddns
  - external-dns
  - traefik
  - wildcard-certificate
