---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.nfs-client"
    storageClasses:
    # changed the name from nfs-client, so it runs in parallel with nfs-client-provisioner
    - name: democratic-nfs-client
      defaultClass: false
    # set to Retain, so PVC will be left alone on delete
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
    # use nfsvers=4, since my NAS support that
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    volumeSnapshotClasses: []
    # only needs controller, and the csi node client daemonset
    controller:
      enabled: true
      externalResizer:
        enabled: false
      strategy: deployment
      hostNetwork: true
      hostIPC: true
    # for the controller, manually mount from the remote NFS server on start, so it can dynamically create PVC (the "crude" part)
      driver:
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /storage; mount ${NAS_ADDR}:/storage /storage"]
          preStop:
            exec:
              command: ["/bin/sh","-c","umount /storage"]
    # provide the config to controller how to map and setup a PVC
    driver:
      config:
        driver: nfs-client
        # some random guid
        instance_id: b265b997-941f-497a-9e3b-74e1c5566fb8
        nfs:
          shareHost: "{NAS_ADDR}"
          shareBasePath: "/storage"
          controllerBasePath: "/storage"
    # allow control to PVC creation user and permission
          dirPermissionsMode: "0700"
          dirPermissionsUser: 1000
          dirPermissionsGroup: 1000
