# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:LuSsrvjU9h1ogJEf3yIMhRmpJpfpzqhRIORjNybN+DUQ1RZjKUfnnzgled+7VuKjDcMRC8qm5QyKIfxv7svkOMGS58oY8iv/XvrM8TAIhHSAai7f+AG7QGto47p68r6E5IwiOaQmKZ7kSytvXH8cKFpCe8BGNEIvQxfPiDUofoCZg3jMVw==,iv:hlS4ZNFS9dz10pOI2xrHYu+wnCtnN/7aM+JesNT6uA8=,tag:tyg6iNo3YYAYSOqe/99XpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNWVHbUxycUdYdUlVMC92
            ZVNPTE1RRGtyc1hIYWZqU0pYUHdVY0UyUVRRCkxKNXJjOTRZRHdjREJSY3FSWlFO
            b3NLOTVBUHNWbDFwMU1OeGg1cURxd2cKLS0tIE03NXdONWVwZXk5azNyMklrSFVv
            QzJNSllaUDRNNWQ3dFc0U0V2Q0ZXTmsKuyEkEZCLkFN+wVGBA7ndvJzz41OO2/9X
            fiqOXtvFcIgWalQL2z8K7xqD0IRYXW6OhYqiWAHhgZLfpFn1WC8wTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:bNCjZNMOcggrOb8gY7a4ea68o5lHfRtIb3OJWaNypGebGJvNvPvJRzjV0nR2ZNdIz8zNWZl84b00WVqqMAjau7o9+bAa7T5XGgacUlOXJzrtCr9Wvph2u4EMyXAcsD00QpF6CMyvgH5IDTMUUgJI8hdbar1c+KTkB4nO5O1zjpE=,iv:p1UNyaJGnMlrzrnU7tRSj9/595j6tKIQmhzvhBn33x0=,tag:5mCX5GwIIpSQfgyj+vSYqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
