# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:oQolj6p8NKlZ7bV75pPj36JX1hGJCZH5F1UrI+KEZLD80lPOLvZN3QHlxPHESqyoywPAnRcaTUYiYUe8opLZGwyk2LfoJsU5Sd7qifg0x3hmZ8wTpIR5PSO8QsYf+Tpfku5RoM5kn95Ry6VGgzHfbv1BknLXMgXHZxr6iaa77YEq9QMtqg==,iv:pkfa9lzpU2Zb1vg5XBXPOCw/8V7ujCefBOQb8Oaolf4=,tag:HbbNyVkiAbAgRBTtC5KAbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-01T19:24:42Z"
    mac: ENC[AES256_GCM,data:pCCfYXtzBDuet3J+jypViOlJc6L0AL3EjOk2wONJ9rPzMM6BfozMaiATVO4JncVAU6WIgz3A41etLJmh05YhSvByb/DXAOlkqfrhdNkoG0vpSHeNtaTQXBp97tefadS/K7/E8n6pDPzPuhu9+PkCAsgpBrr2Q/8GXKm31ROsylM=,iv:WO6JzQdBoponWHuahs1HN/AupzmjM2Zz0lUnEIIg48k=,tag:3B1tn38M6OTU4v8d0vAbZg==,type:str]
    pgp:
        - created_at: "2021-12-01T19:24:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ//T+/+JT4xaJ7Z2W9i6HSbZmMnZW2PZK2vppwj1K+YlcHO
            aLiTi/JBD8yLmCxEkuruo7GCUVq9H1tGfZDsVAig+tKEWWjA8NDF6R6UqiyWgKJj
            Jnb5dEIx78MebmxNcrUNrRoZ4v0Onzh2g15bSqwMM5AE3v1Ezvha3i6hd0/1BV/U
            UKVJugBEVwD4keo66UT3l6VXsiawHH8IUfShh0QfCSzXt2GaQyrvpRN3NDYYSTUD
            XlL4Qa9dtqgea9t+LyNSQW6jHczteGpvGI5fHl91X1ETeo8MoE3FVba9GtrGPrhl
            cT2aFR2tcc+0DqfuiXDUpo/JDzVwg2wvFt7DAuhJgcWKEFtRmNUSVEcF3D2pYOk6
            uwy0TTwKcLn8QfGy+BJwNFpnWvQCKXSw+/N7j11I68yv+HVeygFDfXCQlgY+GzFe
            qDiI6myqjW3RSRBXEhYPyuwUgYyhppIxfdjl9JRkv9l28TSxVB0ZnfFxEIIx/pQk
            ADNRd5KoDdTiTem3AbKgjC/FYYciS/IxtfX95ge0q5wTYPNvK7HjMYHx/LDOWdEA
            lVPle9gtoCMe9v3hzMJR3xooW11CTcISj23VagcbOUSyDk7PrOMHDWPdtzs7XdkK
            YAwYgAQeWOGaYa7uX/6gCAXAL07ymWWBDw6mdt4KiXNKDGKJwrRl/VcDNtlhxS3S
            XgE6v0VTWxvYuQEtQJYhPIAYwucO4ZbQPZvFdUpO5o2uMTfQ2xA4oxC/IYWS6qgb
            p5bHOS9XlNQV8mV7K4YqKH0cTyJuMKiUZnM1XIocPUzfs25D40j4u25th8poQVU=
            =qKPk
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-12-01T19:24:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/9EMOlRqAQhk/2jMbacUQQyBlg/RlDKJbwqN7WXOQTVScc
            Lg8nvhAWMYXrmX5oSRK1Q3N5KPZwTsGt2ouaGZoeW1iAQV3wb7U7L8tru982j3sw
            gfJERzaVmxel5hWsVG6beV3/n0hzGUe9ffTsSu6EOUPbYkyE5KNFFo7JFEXluAQV
            JfSTnNc+1KzlTpuNCJv1V6PcIQQyd9WtAVQMMnMHMjS9WfX4NCYE4jlAKu2QYGIi
            Q5XUwLIQ/Ik+0QQIIXEJ6HWDktiYD1ao/iEVzGHLjl0i3fCRTyauFTFa98FC0P8w
            iexcF0RZdAFmKpu3fbfOeHYgkHG1D1jEbGohLqphr/gq5oAHE6etRPPVMZE1NkvU
            9OcrDfEQpHBGQdtU66sC5o4u5T5F6mNDJAFlpUZy/IVaTIsiV4FZewgiqAVCAEcj
            RLytBe5eMykT4E6zXIlPUiErpATIyZ9aE4en5Dq4Cme1iIWiSIQCwZxCJChvUXdT
            NE4ppJK2SSCb2O64Sq0pmR6QynHXpPgCWu4WGJc/6MBrAtBVx3nj9DevVz8BYQmQ
            /b2Ghba5wERSpX2yQhxwavxrvQwAcLVDCqI+i9t8LXB9t6yC/8GVqYPq8VYPKq8i
            H7UVyWSL4SMIa2PHRLbqHmI6XMAnyAQ8CJls/IsD7pF0KPwRrCqecHhhcyDPJ2/S
            XgGJ43mfB5uHIZp2jKkn90fjfBDyGTaLXjOZxe0iIL7jPd6yH/uQsR26eROrM3Wd
            D3lFdYOmCK35ufddS0ESItIL52XEUbnbrK3dCPQ4O82XUqkgHPv0bAG7E08o7TA=
            =wtTL
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
