---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner-fast
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
  values:
    nfs:
      server: 192.168.5.10
      path: "/storage-fast"
    storageClass:
      reclaimPolicy: Retain
      defaultClass: false
      name: nfs-client-fast
      accessModes: ReadWriteMany
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
