# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7VCYCvUhO+v0OHj/KCSQ0Co=,iv:Jp8sVeY4+GtuSvWO0BmIKxp1cCbGURlZPPRwSKpS6Fg=,tag:v+EqfDp0oZVmjK9uDctuZg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:1BUCZUdYFO0aSzA9nL239pE3SnEJVHs8jjcCHTRwF17nkKK1Vw==,iv:kvfvm68zXRiZ8fPzmUpsidEdcCSk8MH7mAoKRiOzqn8=,tag:WrO9XRFfh7g5X8DyHyprfQ==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:LyL6qArKBpRkPpt2a4Sy5pqlb56aAAmc24qFtjOUEGo=,iv:8Eg3JSrgCvRCyZW48ut2fP5D4bZRGtmfwKgGN2ojdWE=,tag:diCEGd1+PIuFzndD9Rhnwg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:p9dKZg==,iv:AprsOAwoV6V6E5QD25WzCCkpahy+4bIp+HKYbh34pE8=,tag:xE8YvxwmEXUnrgX5fBaAgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bS9GQmpoR245WjdHdmVO
            dThIODFWTERYZFU1Tk82TEd4WmJEZ040UWwwCi9vQWtUaDdUWDZ5aGVsYWVGOVp6
            cmp4a0I2eGZxMnNheG13bUlaUjE1elUKLS0tIFRBNUNGY1BZODI3aWdjN1Q3OWly
            SWlGaitkcDArMzU5OWRRZENJVXNuSUkKuBCXNN/OOnhWUXs23u2Pqj+UzquS4iDR
            uJ9CQfXkWtFWumc6B0Nq894Fqz95OPeVEtZlYkUs9MnhGTATSE5S2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:n1X9q6yjXaOngv2/hyH74TTQk02Wxn+2KXtdq/EXnR/IAXZphrQZWLHVhVUcESm3usJKuRSrCoLYsYfp6MpAr7Ot7BvkcLrrLxl2AMHMl+Ep419kNsgnaQJxLcyA8UFGETH0VJIpvPR4vAc54271yUn6b47kzMuatkegNcZtY0w=,iv:5I/CgAni3d4mk6NwxfsHbi5Fu36RG68u/6c0CvKgCoA=,tag:98hfyV/Zn5kY5vNVMq8Cfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
