# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+uSukmZGaeGjM2XkwWBkvZI=,iv:1hKCib8xuwnW082eb/5kAZXiMxrF7XipoJql0B8HPXY=,tag:WuE+EJNbZhyiJk8VQ0m8og==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:YoP+CEMtcWHL+FQ09R0xxV4946wvCy7pO8TeDBb7J56ROaPoVA==,iv:a/934PPBVk62FW5I3Fb9RVGMYAoYIue7Xv1bmzP5vOE=,tag:J1k3CiWGAeBsLmwt1TZylQ==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:FsIswvgHAZYjMClA38lAzVYBzUijDy+REkL7/6y/oXk=,iv:RRrQf2wZGhPVD1MiVf1vLSlh0i+x66gzg4mRpmgdlDM=,tag:JdNWCDxrx9cJ8wKv61hmuw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:GeLgUg==,iv:pzLlrmhrgSbFmBJABSzVdYUxCHr4NLfNNFLEnYmar0g=,tag:7dYoNIkvxCiSNmlu+xDY2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-12T16:59:35Z"
    mac: ENC[AES256_GCM,data:FKImpw/2A27tZxaW5WBwPFapPIKrMpp5UUWJQmPbamanlSY2Yr1hBtgzIQNC4oULS2KgCLzKADtuGHM7NVRKY+gATbN/UaICDAofhS+vnYAEF/q/izTkR+/lo/Lx5SFZmShQ+YdA5g839FRunMb1VvawjxuvIiU5Nf5W3dWqIdk=,iv:WAlkKTbt8/Yo6iDn2dg/MLVVi6RKVAbp+44NM9lgcmQ=,tag:EnGJG4adlM6U1O6QgJA0wA==,type:str]
    pgp:
        - created_at: "2021-11-12T16:59:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ/+JHB/soHOjBcUaoAt01SuIvOGxHl4dRSOph3GuLNQKhbW
            NLALzOa3WHQnJgjtapTbcG1wZNXbsBQhTsHqZ0z+iNxXHKIoBuhaSTnYdxGlcTVl
            0Kxx1dCmckM9N1wfxHI1yShORkKWZioLLXHuI9aBAnkIEuw0LmV3nyL4RwvGbzx0
            EuqP24KdmYl5ZpkJ24KRxgU45/0R2ljVhkcmTSF0UtKIqDt+vb9I9S7Zhsfg1+aU
            cGeJ5kWyo5esMjHKBR4H/R7+4xI7UIoHlfAN/8r4SZAYb3EfOGBbZ/5GSX753t6q
            A2ETWNfENmFnN6oDRpj8MqQjjiHvuFMg3ngSwl4jY1jVXWt/QsswMRRb6BvJp5kp
            E6hFKi7FS4Ox0Ys6FoYvESQqxbIKT94kyRfuUN6ldk1PtxKT/Y3V1ZjvmcDMvQd6
            UmrkUNJKoYW7pXcGwRNMWeq0ZczYdkfxHXJ27szANDTuSRw7aZGAmthPZptcDcS0
            Q+7Mwx5SmHWwUjsdydkrZo0S+DGEeReZ2gkpGJGl+fDgUM+vcL688Nq21GDokVu3
            DXXkuvbLdoRwsC7jJrbCj0xrmIfwUsvu8gfqUkHHmfB98+B5N+nra83gvTPWaY09
            DnRDsxaLPXP1hXU5vGQvPNRVqgc39D9bTOgEEH+CF1RW65FCnX3gw5QYca5voz3S
            XAFjW+6QFjoBQzRX+e1lVQh+vuV0+VDxQoZDlWTqJ1xV7sHNS05b36p+h2Xl9Iz/
            AtAscMwihwturA1zFgYY2tntPmuFEXzmGqlloKLvDPfvhEOZ7dH9REs+qUw/
            =C+jv
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-12T16:59:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ//UBrydHXYdzHmvq9HpKWTXDumokCqrgOgwvyrRFw6XprW
            ve5wSem7u0+d3D13QlaNR6KFqkJP/5gfTo69OBQZbGXAXm7cDGcN33u87CJyxtWO
            CGGUdpFtHz4pCS2iY9OH9Iy173sI+uC+kBwmxjccBXDKy6h2vWdO7VEcIKugvp9u
            NXGnPHwy8+g7kVDkmtt487WvLV1rqnoDf//LW5G+VZWkkkeaIPsUB40EbF6cAiaw
            Q+LNtO2JE9FXsXLGVW/80ay2hmLA6EyyuJJQptf+LV13v8wpWp/W7UeR361LyVMR
            kaihkVdZFYnBeLwvL6Hu6gQTSZW6iRAeIMWybaKYmcHJvxWQ1ZXHLMCuc6JOWaoA
            fgbs/XeFOlb566Pn5X36DUSSRaJ39dKPhvGyaZfYE0HWsq7v0jpuZtJJyJcn2/F1
            Cyc4A61X/Ep2w3kdF64av9ScZG0v24/KMl3NuYiClx295dszFKG8H84DJ/UxH5WD
            0NZbp0OkPujid2ADXGCQ9njfCHQVGh3P4q52oSqX0goxtv+riGWGbqCNctXd0bte
            L0trAwlRGUdAFiBSoEe3A+FWOhBGe/5J+bgeAJqh1I5Uhw0Dp7a1GCkjuFPXpn4N
            9a+Eu470TwUk4lXQyujyD5ay9RSS8QfWk8O2yDKZgy5eUYN/al8sRr+oi2rpX6jS
            XAEfTLZLWQ/O6CCb58yHAF9YgFHnKZtO1+FZRVu15hpSAmPIfI4U7KBaXQydLeHf
            ClkH9TCABStGMkrYR/iYhIv5vPswYBE7AD2EjMXLUCZPKGmesdA04PGmwUyy
            =+XNy
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
