---
- include_tasks: locale.yml
  tags:
    - locale

- include_tasks: packages.yml
  tags:
    - packages

- include_tasks: network.yml
  tags:
    - network

- include_tasks: filesystem.yml
  tags:
    - filesystem

- include_tasks: user.yml
  tags:
    - user

- include_tasks: aliases.yml
  tags:
    - aliases

- include_tasks: fstrim_cronjob.yml
  tags:
    - fstrim_cronjob
