---
- hosts:
    - master
    - worker
  collections:
    - devsec.hardening
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - ssh_hardening
    - os_hardening
  vars:
    - ssh_banner: true
