# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:HH1Ufd0KDO0A37Rd668vX44=,iv:qdZqz1cQpZNTPB4/3QXePbRZ1aj5HtG9Z6iaflUbACE=,tag:Ii0sVuDcIWesXt/OOCl0qA==,type:str]
    api-key: ENC[AES256_GCM,data:Yk5Xdi3/bgpPyWdRgQQU5K0O90y4SroMV1hRZZPcdIxji7kdpQ==,iv:ASgoT2RK35bfeGO2f/zzsIj+vCc/HZjFq4zaK0V3Fv0=,tag:W133GI5PTFQcADat9FfRhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-09T18:10:19Z"
    mac: ENC[AES256_GCM,data:I4+oFTu4AINVLBRmBtdiuOnY8Y+Z8cZm/k0ClytTqPqPtSg6Bg+kfHqhOHTXPLuH3ryYANl8DVKpvcCXYSJuTQjwXl7VbeiB5jctRTuC9wpD+768nr3rpZiLK7F0SR9HsUNiHJsxrbTovTZX5ifKiPb+ENy3LDaI9bag/FlU6I4=,iv:GbIPi9SQqmL0wJuEdThS+VzJ2SWBx9ygS6J2QfM43D0=,tag:grsHM7VU8HQ+yBXdn8gOyQ==,type:str]
    pgp:
        - created_at: "2021-11-09T18:10:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ//TDXq+kV9aIsH0iKb2JNWn+zwdPg5/lW3Ph8vF5gpHBpZ
            ezFaxMQMEtR+wnCWbZhPlXmW9DBlch06L53uebX/+Qc6ScvXB3FmasFnQeM8hCBw
            LPbbGEwuMMgRf6RX6Bcq95u2jvefewGdAqUm0L+4IiPW4rU9urkxDeJoOt1UH44C
            H43eR+SCAubzR2vl6lo/Q5Ahst32iDwTPzUlffv3F7MG4T4tvuczeb6fBNVnLppN
            8xFDY2aus6EtmN8k5iHLAMZEvHyDuP8QZiQ82YSqBRgMgsB72Ih3zyMEsBb6WGeE
            OK/FdHYVshfG7bpaXpeg3j5XGhr0ldYPfa9Ddi4+mfehVbiz05vLHMloQhKJJaBL
            tSQ6sl1BheRci0GPwhoVVLvDlRnmfls5gSRijz2F0hs0QIOwnkeZBmO+pQM2zXvL
            CgBR8Mco0rc8IGf97BiJb9+f85H0fcV+pT1AFgdl5bsF1Jkn3fNbEsxNjfOjnm6U
            OU+f7w1h9hDBLi7z4TPasYBGcZQIf7ZjQAcqqzi+meXZExE69aZ8EEgBuyKZDPA+
            mMSTqUhSnIVSaSF39FWd+gyZjzF3bfJznqo/jTqosdf38tIyJIs1d7Vb9YIInNZa
            pKSH5NjXtiyQsYcATummhWYsPWVPwnGkiCHferoX5Al3iQ3HXMp/HNkxoD75RdXS
            XAEnK9E+p0tALFxyE2RynKH4UiNxDrS1bTwrSE54ldNoXN8Ge29WR+HB2BjfoK7M
            23tqFMANRnZSyMd5JaKBWZTQ3spFJbNGhTp76o1YeZvCDVP2rsmVx/gHO9io
            =OKGr
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-09T18:10:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gARAAkV8o1GKqCWKMh1X5zfE5LI8+PJOy2nzE2TmbDyQxf4TR
            uMHoVT0gZRLfe5o7nD0KkTK0w88CpGNxpETn0MfdH6bRJR8+MxzEuUAEqKfrcMhQ
            h+XjgpIHThO3w+upJ6NdpgYmSzbSyQ05VBVoGRD8yhyw40rRO3TUTTrCbe7odvsG
            15/EPCGaIjirEWwd35XGjVyWiTyf5URGUziOZ6YTNczkib7WRxKsU6RHKIcxsZCh
            vuqmfh3OxhsAmpjFhMDDRPy7lg08CRmogo/WlzPjhzsFqGrJkbfEOUHrvy8YLYvn
            savNHo/b8DyTjRv3/r8WUa8fqQ/gTD2tVXSpiq2uM6/C3+T1wv+X+0mmcpQTjc5r
            1GZr2wBVlIA5DHHUyHYc8rEKhI6pt3oIbX7typIf7NBInxfovU9SILdyUbyUiPwA
            y6sEXk4XcJaJPmov46BhwlJUnbgPZ9FOakeliFbXM//LtuBcvFK2eMmcGAcqZn6T
            bsnsPS7L93ZEvkgXWHpvArMasAOQf0hj009FUGJMtmlv+cP3mpSlHeG44agSn2eD
            qtMv8RAhaygFxCbeMKOTWf21bYbQkVybAa02LaaefpTEHGc3ioftLoeOQXPld7JP
            ThlnCpS2vCJOj9Flzc/mUnJdBaD8Bu+l598RKOE7zs1GAiglS32Y0YUBpv/+cHDS
            XAFu3PFbO2exZN+JoBpkuqAzFKtI+JKbqNxazEIK3f4wf5oh6fgqX/OPgqPrK1u7
            NxHpB2MKJ4VXCQN7hQat8ZDPv2o8j22Q5huaElaxd+aLqbIO+WtkA34qaATM
            =3XqA
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
