---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /storage/docker
    - /storage/docker/apps
    - /storage/docker/data

- include_tasks: cadvisor.yml
  tags:
    - cadvisor

- include_tasks: node-exporter.yml
  tags:
    - node-exporter

- include_tasks: watchtower.yml
  tags:
    - watchtower

- include_tasks: promtail.yml
  tags:
    - promtail

- include_tasks: docker.yml
  tags:
    - docker

- include_tasks: plex.yml
  tags:
    - plex
