---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicas: 3
    env:
      TZ: America/Chicago
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        annotations:
          metallb.universe.tf/allow-shared-ip: shared
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_BLOCKY_ADDR}
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        annotations:
          metallb.universe.tf/allow-shared-ip: shared
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_BLOCKY_ADDR}
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    persistence:
      whitelists:
        enabled: true
        mountPath: /app/whitelists
        type: custom
        volumeSpec:
          configMap:
            name: blocky-whitelist
      logs:
        enabled: true
        mountPath: /app/logs
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 25G
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    config: |
      upstream:
        default:
          - 9.9.9.9
          - 1.1.1.1
      customDNS:
        mapping:
          bazarr.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          goldilocks.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          grafana.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          hajimari.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          harbor.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          loki.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          minio.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          notary.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          prowlarr.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          proxmox.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          pushgateway.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          qb.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          radarr.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          readarr.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          requests.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          s3.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          sabnzbd.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          sonarr.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          tautulli.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          traefik.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          unifi.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          uptime.${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - |
              /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
              /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
              /^(.+[_.-])?telemetry[_.-]/
              /^adim(age|g)s?[0-9]*[_.-]/
              /^adtrack(er|ing)?[0-9]*[_.-]/
              /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
              /^aff(iliat(es?|ion))?[_.-]/
              /^analytics?[_.-]/
              /^banners?[_.-]/
              /^beacons?[0-9]*[_.-]/
              /^count(ers?)?[0-9]*[_.-]/
              /^mads\./
              /^pixels?[-.]/
              /^stat(s|istics)?[0-9]*[_.-]/
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
            - whitelists/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:${GATEWAY_ADDR}
      prometheus:
        enable: true
        path: /metrics
      bootstrapDns: tcp:1.1.1.1
      httpPort: 4000
      logFormat: json
      logLevel: info
      disableIPv6: false
      queryLog:
        target: /app/logs
        type: csv
        logRetentionDays: 7
    podAnnotations:
      configmap.reloader.stakater.com/reload: blocky-config
    resources:
      requests:
        memory: 477M
        cpu: 100m
      limits:
        memory: 700M
    # securityContext:
    #   capabilities:
    #     add: ["NET_BIND_SERVICE"]
    #   allowPrivilegeEscalation: false
    #   readOnlyRootFilesystem: true
