---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config-v1
  namespace: networking
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-fast
