---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: v7.0.23
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_UNIFI_CONTROLLER_ADDR}
        ports:
          speedtest:
            enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          hajimari.io/enable: 'true'
          hajimari.io/icon: unifi
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: unifi.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - unifi.${SECRET_DOMAIN}
            secretName: unifi-tls
    persistence:
      data:
        enabled: true
        existingClaim: unifi-controller-config-v1
    env:
      TZ: America/Chicago
    securityContext:
      allowPrivilegeEscalation: false
      # TODO: unifi sets JVM config that prevents this setting, look into how to harden
      # readOnlyRootFilesystem: true
    # resources:
    #   requests:
    #     memory: 1000M
    #     cpu: 25m
    #   limits:
    #     memory: 1250M
    #     cpu: 25m
