---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 11.7.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    extraEnvVars:
      - name: TZ
        value: "${TIMEZONE}"
      - name: MINIO_PROMETHEUS_URL
        value: http://kube-prometheus-stack-prometheus.monitoring:9090
      - name: MINIO_PROMETHEUS_JOB_ID
        value: minio
      - name: MINIO_UPDATE
        value: "off"
      - name: MINIO_BROWSER_REDIRECT_URL
        value: "https://minio.${SECRET_DOMAIN}"
      - name: MINIO_SERVER_URL
        value: "https://s3.${SECRET_DOMAIN}"
    auth:
      existingSecret: minio-creds
    ingress:
      enabled: true
      ingressClassname: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
      hostname: "minio.${SECRET_DOMAIN}"
      tls: "true"
    apiIngress:
      enabled: true
      ingressClassname: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
      hostname: "s3.${SECRET_DOMAIN}"
      tls: "true"
    podSecurityContext:
      enabled: true
      fsGroup: 100
    containerSecurityContext:
      enabled: true
      runAsUser: 568
      runAsNonRoot: true
    persistence:
      enabled: true
      existingClaim: minio-nfs
    prometheus:
      servicemonitor:
        enabled: true
