# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: tools
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:TgKoGBPEDwflXaXt,iv:6aC1yuXE2S0DXr0KUO19pGl+7g649bdLAj/j3aDs+sU=,tag:XXeleTddRpbjcoeRxcIHAg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:fTIi8+ISBg==,iv:0Sca24Y6oh7xkuEg4Ntw59BzGNl/fVIyl/5INrFitPs=,tag:KSDCP5SK/t5Z5ewJXCMxIQ==,type:str]
    MINIO_PROMETHEUS_URL: ENC[AES256_GCM,data:boa9AxmT1/OQn3D8r9C3FApeARKv5VNKaf0ALkqEvxAwiw==,iv:7nA5ssC4YTj1FnpeEFs7CnReUSkQXgDHIQNXtwttAVU=,tag:JI8oUYIhiz0nU4w5z4fziA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbm0zck9zL2NacVhwMjY4
            NWRHN21qV1R4YWlVUXlGcXp0ZDZ2K3dYaGlVClNFa1ZmWGkrNVpaL3BEVmJXVC9G
            UFE5ekIzWjVKdUZNWVJtQUFNV2dvbVkKLS0tIHhJZkNrY1ZObjFvRDZCN2REYTBt
            SzFxanlSQldlOURuQzBBQ2ZucnphVVUK+5BH8VgCyKX0BCsf16pTxYGaHjfPR+U0
            NdMFkDuR/GuBw51yrAPs+ySmgkMasrMGnrmCBo3Ls4S5WQSkP8jouA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:FxE9cmEG3sVOeJkUTXISaf8/WwmJZIrdVHmRYF4sVxIqDYdgKNaDixs6YleLwRy7eqhE4Cq5GToNUwhxe2+yCZ5HH5O7eKRAxAuIVhTMYB0SJa/zYeRFX5sriMB/jQeFlxZExSJWuV9dIxoT0whD6c5Y2FamlV99dFLXMIumouI=,iv:w4OfV8h1R7YR77fCtMdDfUHs8F87SAUDze3DX7B9TmE=,tag:p8IxSlI4sem7VgpQHorzTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
