---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: louislam/uptime-kuma
      tag: "1.11.1-alpine"
      pullPolicy: Always
    nameOverride: uptime-kuma
    env:
      - name: UPTIME_KUMA_PORT
        value: "3001"
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
          - host: "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime.${SECRET_DOMAIN}"
            secretName: "uptime-tls"
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        mountPath: /app/data
        size: 5Gi
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi
        cpu: 100m
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
