---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config-v1
  namespace: media
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
