kind: Secret
ansible_user: ENC[AES256_GCM,data:G9GqoP9T,iv:XJR1STpWoWLeaS4YGKfLBBM3MrqUga5bdf5ggbOoH+4=,tag:2IVzbAjw5nC7Yb9ByWvJ6w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:J+YjE0ttsraVG6DR,iv:zgyQ5gfeJ7zjbMOBjHDKuVyV+mX6ISGHNfKIPwt7UsU=,tag:F4RwajVm1W3xFWfMpFQhGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ym5WUzlwd2NmTlNHTlVG
            c2xjT2lFQytqaWZ5b0FpK0hLMVNVcEtiVFJBCjFiS0t4WjJIM0tYdXNvRFNXVXZO
            YUlFbFpiaG1rL3lmdUpEMWNkc3BuZUEKLS0tIFUvSWFHQ3JoQ3BMcm5iMk5vT3Nr
            OU82TGpiejhnZjdnRlgrK3lOUHVsbWMKOtw0zz090RIPY2GxmB2ZndeHICJzdnTs
            rsgtlwYmlDfJUxQAq1jdFfl6MUMq5fXn4yIMVQ4PMrNuHOYHNe7JXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:45:27Z"
    mac: ENC[AES256_GCM,data:WEO7oPboia3RfPb4K7in7/7mv0/oNccZy0m/vF+aKrNraE60nmODl3chQa4gylLLou87RwA37x6VfQ9IGtOod61rnS4DngIc2MyfI+5yutL/QrLHGQ3sBz+WASJtObMliUGVEINWHI6sLmL/kB/ZflFsXxmzuis0YZQ9t8sfBws=,iv:GqCs3F5xURMr25fT12hEgjcwQp9/hplSItAK3BiZIog=,tag:8j5uLctVD96QJqDeLFuFfg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
