kind: Secret
ansible_user: ENC[AES256_GCM,data:W2KRSojn,iv:hNOY0qutT8LRUXVIEKMw85SUYn6ipmvlRbwr33K4loA=,tag:HGOkXrLSANgR4itpzggYrw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:V+C1C753eLBASU3L,iv:On1I3fsD4UouweZAO11QC75aOez9vBvzphO1JdLHe84=,tag:FUh0ZHgQuP+9/w/VKwg7Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGhEVnJXNU9SR0JoWUtT
            SWFFRkxBRm5JeVBDMUJYOFdwSVJIdERPdkJ3CjdVYnZNZWtBT2pnWTViMkpXSDQr
            b1pTeThwMjBVR0NRQ2pUNUdCclo2YkkKLS0tIEZ6czJMRi93SklRUjdrL0l1Rk5V
            ZzJvQ0VGU3RpMGNrb3VCdXlHRlhjREkKmk2JbGOvia4Lih9XUpCbR1u7E+rcZ7Xs
            z5qfnLaJ8vg6fAiHelZXps0KZmwqX7/miQkOcoQn5uc0vckhbPatXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:45:27Z"
    mac: ENC[AES256_GCM,data:pUoOH0t+qX3fdBsWNgfVocqvN/U0vLBvt2daG5y78bnQNYSd3oXD+TIA2ESlAnVN9iydw8LgIHZVobv/wO5eAIR617vBSQo/SA++YvJnz8EBBXm7JEhoM2wv/wtubuoim9YCXoTZqgobXUxerix4LcNg0RvGu7Rba9PDH0huB5Y=,iv:2ECzMsQtH7Ukfn+qsMn0O32fxpfxKu31yIblYg4ogrc=,tag:wi0yekEEu37uPfJR9AsbHQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
