kind: Secret
ansible_user: ENC[AES256_GCM,data:8OI52s7Q,iv:OOn7EgzDtW8pCxy/crXpXrNuQQihZPc03Nu6jbWMAfM=,tag:IXb29KppD/cOOuwExDdiHQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Rq2DabLDs7MeznIP,iv:rFZALFGiCo+fKxIDMvTD2vXEq8vy5ur4BarJLewWQSQ=,tag:tG4M30bmS3o2e2yNdU+Upg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeVNzMEZ6Ny9aSmFWZFRB
            ZjkzUFhZWk1lYTM1NHJMTDNWOW1GZHR5TTJvCkFpRmFOL1lLblg5Y1dJbVJLUXM5
            WDJOVkNjb1d2QmlWZDJCcE1lbkloS0kKLS0tIFdROXprNjVUZVB6MnVFdCtvOEtl
            ZTlqMG1ISlRWZTZ3NEhsT1lVRVROTmMKhFQL5GqoXMMlwk/9gAEq+Awd5/jYwY0i
            fmNXuAAP4c7EzrV7B+2SH9cjdtcql2x7ju7COzaAx09+VrhzomLUsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:45:27Z"
    mac: ENC[AES256_GCM,data:ar/naEty35tl3RKqM8+5ug3xhdtdNHQrg6UESrAasRme/c2b+Jc87gjBvmYHG0+MoTl4PyVNoT6FnjzZdtEA80iIkxRRZkEolXNBq+4glNWAt4ETbpcbZjsJI/V2HSP4x8jr5CGruM4pXKJsPe4Tpf9ftL5shzpT6veun0warxc=,iv:Ce0dpmPbrF8xykoEhuA5R0Y59Dsa28ZIuaowGUkZv7E=,tag:7onlbGsee2UX74Yt5Pqueg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
