---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-v1
  namespace: media
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
