# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MPnnFchXfZBMTgYSg+2j,iv:YAVmoS7U7URJI25WHGuUEuQLxgLtPHWXJH96uyjbVJc=,tag:dnM+9BlMEpASAM4OqhC53g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UdEmHx+iP5RF6oUsD7Z2X8E=,iv:4Hibf5HrsRdYDH95IOO0FPdfeWN4byAoeuZ/eSlI4KA=,tag:BwR7Mc8KMwpa8C+VF909RA==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:5UVVaDmysO2ZLy8t,iv:E5XIIIY/5MFcL0u6vWHd+TWwJIuu//UNkAXA1KbICxc=,tag:elmEkBk/9iSA2EcR+tjMJA==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:nXIwSItQZub4w2+Mjw==,iv:A2CVzEg6frAEgeOFvjcICRW68JxeMj+WvRmbytJMVB8=,tag:tvEoBioLaw6KgXk9Y28yzQ==,type:str]
    SVC_UNIFI_CONTROLLER_ADDR: ENC[AES256_GCM,data:H6yWBSE+NpDKhgTzLg==,iv:w10EqOzBUrm7TyNnyZhfUtUfF1qEBJBtFpmvPvBSQrU=,tag:HqHkclUKwkjlxFG/RYTUOA==,type:str]
    SVC_BLOCKY_ADDR: ENC[AES256_GCM,data:198/QnEjaq8xTXP2gQ==,iv:QKbMdK5o6ror9xXEgE56E6c/FHYMcjifLDhs9eZ6SQg=,tag:YpB1yYh9qkxdT+pultCz3Q==,type:str]
    GATEWAY_ADDR: ENC[AES256_GCM,data:gBcIMh/gL846Zl4=,iv:o5RLfgCZ2xEtHEx+yaI/NAxNg31DLI19atT1+DSEw84=,tag:TsrUpVGAGPVD9SdoqRUbNQ==,type:str]
    PROXMOX_ADDR: ENC[AES256_GCM,data:/KnylWFTaMsOo/Gp,iv:yaz0yQwQ3/qZf66OXoRbqrj7j/yACar7e4LIwkieUDw=,tag:WNqX7XADWfy1/zktrY3w1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T16:16:15Z"
    mac: ENC[AES256_GCM,data:wrZdM5UXqbHkRT118HcMk46wr/u9ce+5YcFzEr/naVNOZBHpG58t5v2ACBSeaR1f4b2Kp1rzTRuSa3FLdYjVZilEDmGNogD+ozbbMTkAa42G8HVWlJOJLvYzqKBhKUaoQ09dMicHsaMGTZm1nY7cTmLSeb8ThGgN6cG9h+dDaMs=,iv:bYJ+qbmcDZaAYIkPgYibwAO8JjQSX2t9jqH/vuMvOXk=,tag:2uqfh09MUubRWRWGB4aYqg==,type:str]
    pgp:
        - created_at: "2021-11-13T16:16:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ//deENWQT2g8tRiOFESy2LCgiNmdTyTOyqUrTlrKHL2nWt
            60GfVkhBj38m0ZUYtoUHs2j0q+y4MgjKPM4mCgALsJ12ZRwqmWYONFspecfMwXnP
            wIabdDD2flxeUSTGLoGwdnt3MnQe2j/GMtBLvt2LzsrUbxTPJMU/dG0YPtzLCRup
            RZiLk+bJUaMeG/xUdFlVs2d07uw7mnTmubK/LzZLjGJ6WC00IMGJYgJOeueTw4VV
            JR9BUTZ4BML/BmiKcT02aRy9cYvXDgyHkMOwVtRlF2JR8JB9v3+CApVW3Gz9pfdg
            ZsMIgvGRgCDtO/kCSJ8Oc3obHD9yohcF9BpcsTR4qffvmMYH0hlk0grvLn19gSyk
            E64KlSa6HqmsueH0Xn8zrqiL4FrykCp8yPDGWIO7tjC63CwDCAkH6Ha2M8Gsuozh
            7HyxoC//hhwN7WcAwj2Vqj4ySlUhXb5eTNa78vXJ+140zZkRnDUjSJ1vo1HowSbE
            I+5i70s7BKtL6CCk758ZQiYseRyibrGlTXgBf/krvPnCuRJgNLV4bMDHhY+dexYm
            Hj4OSvgood4tmGQKKzN96qxjoBeSfkbRBllFnoL/GbM2aTwYAX910gvr693uq7xs
            Y1QqrnhOUXCtsfULtdkGlQkDj4M+mEUHjGr3lGtI3Gg3X51NJSCnyTY4MQy5S6zS
            XgHgnwAle8IDK+WF9cuL1voGUxowBzuCxIlZNj9ekCa1UdfSQ2aqXN81c+xe8Vlf
            QCLoxfSEv8acjHj30y8PZVb/1XvdhEzL5gpiML931jesNIgpROgg2J3J6jQuQ+Y=
            =/uhu
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-13T16:16:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/6AvOn1RRB5wWzRLkndcXpLMpTUk15Rv/kIfsynxZAVel3
            XjDy90sLS6JRYPtziSd7iNLvjOj7iqX9dY/WnqfTEJChAeg0nOcXA9eU0CFsYgZ8
            a0fipEesRb05YEHTS6exMtYtq5982sGp9sVqnhHRyknRuB5J6YHnsazzqXx0smdU
            /1VNnUX85rjiyHRuEvt1R4HyXGqH0Blrk9MHee7KCsYm49kp4vslfLTZpmQbpyxV
            ko+30u3cADa3Q/w5UdCOd+ShZuYDrWgt7Dx4se30NW3Q3cmfiam3p0WmwyVcQqfT
            hX7C93tSYomQM5GQDc8oVJqIN6nviffoSX7ZQQ2LTmM2fCFu+j9WeeoiVeNv1drC
            M9Yc6JulVuCzXo/LOvd927JrQyCuA+DzJU8VJKHrpoGQ85uDQ7HK9k69adGFTUbh
            doq5zBjcueTg3Ug+pL74MWc3ACAUIwu49jOs/Lwn5OETt5g+U5r7YOu8cG1pTOdx
            wNIANSEPaNneno+tosM1/VTo7k1HXOTVScl1mxup0T9u5/SbPOBIZ0aenBw7Dk2q
            8rCGM4It3Dd5lU2ZmNvUetF7BZVZnjiLqrt0hlzeiks8/+zNAIYLJtnOi9eufhzK
            8N4yY+jKPsF5OxHioSAFGFDBGQSNfvoJQsP/YTAShFvHr5BqQvf/Wbkum8SS6zHS
            XgGnjhySdkb5d8efj25X4Z1mx9kbOveZnWZo4O40vIMQPPq+fBXaFgAlmx2NPRHF
            K8LfyZ0bm7DoZlP+9Bekjwcnx0WGvaOyoKLJBlOVmAL8NOG75r6Cte27+NqlfWE=
            =KM0Y
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
