# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2Wp0thv9pp0+lRZV4XNI,iv:R1Ke9RxP3cCTwGRVFD4Fr3E5W8Ko79q7sMg6o07TqkQ=,tag:b/+kL4zpFRyvJhubJWUJ1g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LUtIC6Whkk28tSsrrzr0XWw=,iv:n3W71zDqwQf2AmOghsBqEbUrAC8dSlNYlukic2k9S4Y=,tag:UUG+5XzV4A0yRAFcZo0eFA==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:+mzaz4BLZo2ohX1x,iv:JWFAm2QJWZgp2nNU4IbhoElcsitr8BcgKjYek3WiUFQ=,tag:4E392aLciRukKRsWFslARQ==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:aVSXXyjXJpd0YLGvnA==,iv:goXHoCUnjGYMe4KFdNE5KjGdtEHpTW7kZ7hAW8AZat0=,tag:GLqF4g4JTCg9uvVRGiIRlw==,type:str]
    SVC_UNIFI_CONTROLLER_ADDR: ENC[AES256_GCM,data:vgkgcA2JZ7qOVjYOkA==,iv:THJrhhZDmaC7gBQsdnVwwxEmwbxObifvNmq/qyrHwQU=,tag:knBHD6ahxD+PEDqsryRI4g==,type:str]
    SVC_BLOCKY_ADDR: ENC[AES256_GCM,data:rURZoTPudaWHaPMcqQ==,iv:Ee23ufzxu0nh6h94qS1tfcgX2HxpfQMKva3hUWTpK1s=,tag:Ac5D5qbwVHYwW29CCbsVaQ==,type:str]
    GATEWAY_ADDR: ENC[AES256_GCM,data:ac+VaosRalAScPg=,iv:ZNCcAed9gRXHNiI9d/iZclqg1Yhmju0oWUuEgAM/d9g=,tag:PU8O7ILe9vdbwjXKPPcnCg==,type:str]
    PROXMOX_ADDR: ENC[AES256_GCM,data:Nd5h3pKH/ca8n9JS,iv:ZZXB7OlXVEuV8bNpP9j0GVThuotZqrSj2iT8T+I8z7E=,tag:vXeAbiChL4Iz3MUH0TvcUg==,type:str]
    GITHUB_TRIVVY_TOKEN: ENC[AES256_GCM,data:Ez8/8u+3CULACtBMCKXZCKfqZ1cAdq/qu0/ehIKj4vYd38XUNlP7Kg==,iv:CUqW++GK3vDTw6W/at2TW+8vBhT6PLVvatKyMYdNqmQ=,tag:w3WfQsXtlIkr06NVTJN0Lg==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:wJRB0JfTisDcLMRz8YbE3anLEPjytj9rLpSF8wEEJ+H10ERaJzBDZj9hk4KEh7g01ugFWk5bFwdm9YOXryRvSm1XRQbyHMgvcgyRGnJbkCgo0BrJmy0jxm0wKdUf8Q2BBClald4EqiKGUJ9Dsv0wtNGGCI+XQym7Z8Hl,iv:ZEW1V4OE1vmuWenzsr6CRdrGaGan3Bde3+0yK2V3ux8=,tag:0D4DXdBc/gT8sfpsZwXWZA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:HRYD0w==,iv:xRusNsyHollOT6HE3adYZFLu8H9Lj39rP0UNae91RXQ=,tag:4Q+gtDNZGYIc3jKaneukHQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:X4+R53v8qZ+YCcwRAqWrpv4=,iv:Pd3iLIMHHfEaIf/Ge8+dCkvbkpUcW074p29rb/7TF10=,tag:X/tFsB6Wjh84cuv3I6FdJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-01T20:30:44Z"
    mac: ENC[AES256_GCM,data:t5VxBrm5+6s5QXMjveI1KjLzV71hL+15SBe2SjG+77trJ5hpeR/ctO05PHEBK8WEoTHYUJq/AaqkWTSLQC+DwPmpB7A/mOtuhxr5YeTg6bKjtScTuBKnXQ1fkUnjQyOuzBnjcRsKVm0r2VQ2tituNiw2jbBeNnsnxje6hSeNT6U=,iv:7LSjSVixkc3482j7NgIWa7mQZf0jNqWalFuS4opvYd0=,tag:UNqiP+0eGdGhcSXtvrdQaQ==,type:str]
    pgp:
        - created_at: "2021-12-01T20:30:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZARAAr8kDBMxFSUa2f+BxMHVgw3KmXRPL871CQftqWRRJx6sb
            2IsSmG21FMhpsd3nOQ1pa+mcCrXODmUAbPMR8HMObZzHyLbHKu+9ulXFgHzvVJ+n
            XEbNF6Bnb5x3k/L1MyY+6GfVrSE1vibTQ4Dbif0FMsRWNsb7EchBxQko5NU8hS3q
            0Zq8VaNZvFMiCVqGLms4E4nHw+xjhz90v4QRXZtdubHAwjJt99wO9rq+Efh3RNzs
            XEtmRiv5nWSRdRCl90fHii1KRWYb7Mqxp7iZZ6j7pGn9Fx691fVcTLxDdwFpKDTH
            Y3xmDOdYCf+NfRpKc0GwkZFfBCD2cfPKxI344rtABacw0mS+Pc17qQtjnXOyNg+x
            QhAM4u1tO+3U90rpGKHrtrhi1x/JBJkjrQ5W25RAsUCt/CIkgyalRQVSZ59EXj73
            /GRYv660ZHChYYGAf01KQy20G+LnRzU/rrzm7QLHG9lEj1vHo5KdCKyEv4Z3SO3H
            z1l+1pOpAm/6feRh4WxdYkHDMw+KIOssPQFcIcl8Eqnwxwi5iOMSTOdkq3YMKGKJ
            E/n5henk1WPRNX/JViuVvatSTaIhEaapt1EnJset5mnyl2IVyWyFtPO40g47IU5U
            +WcQDlGiYa+mQA3lhR8tWh3iqYsrRzYO433l9hPESPSZjDlB6JsVSJ7ud+u490rS
            XgGMrDFqnSRv+b4B1OmQHdMt0u/FXc5bEiIhDC8oWsRi9AZ3dJwE432ozQH5zEYI
            gjNV6dljEggtm5ff/KAbgNSAF/qtSJTjL8vH7PZDSVyAAD9PVwNHTfFmES+sfFs=
            =ymIN
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-12-01T20:30:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ//Z71AsygjW2lvRd0M9EO7mW7QsKCPBrtwuALpeh1GmgvQ
            zklEo1vcN+yZTmvTK0UG+6wMdA+9kwD1meRdLYhzrX1YAAVC5zTR2Du0RXEstzXx
            bTru4YY9+qK8d3x5AMdCrb3zh+ZWx1B0SSBSYu1xK4eqyfC86E0/ZZj0/1SUQJjy
            IyxhfW8AQal5Cqc7ac+Ru6ges+qwz1ySXk51qRnVz7dzeBlum/PuZKZj2vVwSmPn
            mz41d8on18kr8IUEQk5PzErh94noRqmckkY2xmPftqgQsbwgKfndQuxhkrUXcSos
            hqSS/LxhWf1K9Z/V5edoLv3iC8lZTjU38f9uH018MF5zHynaink2wn4dEv/sS4Or
            Hdh9Esp+5BVNsxt08/ayornh3kCz1k0qP4H5MgCaUYz9qWERTwRaCJOZJp5NCRb+
            OtnXdcqwxUtA6HJu8p+KLstUbR6l4TQmSwmLGBAU4ayEIWE4UXCVyr8VWLJWCvjI
            m69r5jFSm+2KOvVTyKScxp6t1YvUlLfGqP4lYp61Bpq9EZTibloyU9+hV2YjG+5e
            OIjOB/nZSSGsTHADI0oxBIFZacAN/6GyRobSf3a3NLVRt2d2vCCN83PBqixfoxgr
            k5wVSKhSzUkjmdV+vUgeDbKaWTHfc4AnM4HfmeykiPaz5QkyomAYiZJ0VizPYm3S
            XgFXYJKir3OGYdQ5xyQKyHiebBqL9lEUWxpREzrbbsWgzrL8abNdJ02x+fdkU/Y5
            RS02cROFe3Su0obL2hbOhmXzXVM9R1lNK5YQut8JA2Sw0yOHecTT7BjPFhqqTp0=
            =zSP2
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
