# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:U/BVceUQ0PSC2UyrBUkj,iv:JRkgBc49ed9CdV1kbf8u4GDHKSTXnOIRsukyMcaoLWU=,tag:UoPhNPBWyHFtUXjQW+B5bQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qXyGdve4Tkhl/gxhieP2QMQ=,iv:Pyq5e+3W/z08ehCCQfn5N8ABc6l2xTGg7/qLaqgPnLU=,tag:xcfRZOskhqCfxs/tIDn5ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-03T22:12:05Z"
    mac: ENC[AES256_GCM,data:dTJAI574/pxzhlFrTpWh+2kOftZPWuB2YvJSOuEN67BCO73DsSwIe94bvs51s/hPnZ7uQPyzeo0BlBjCVX2gpxC4PFwSebKMl+Mh+3rrhfbYDeUnNl/1sa9h7Zy5BJ1humVllX1WsAbXtxplXfOE6STwiLwUifqZFcv5jmIFRa8=,iv:EcNLlURy5LLyxxvwF83RxHEz202rxSUAh8IY0pa+klg=,tag:Th0e5AgwdbDvX6NdLUY2oQ==,type:str]
    pgp:
        - created_at: "2021-11-03T22:12:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ//VChIu7qQR3NlUrSTr8lzsAcylLO/sLsGQ2cYVgiBVXjE
            Uw7FLZnnXrVMmFhLVH4Uyqf6JuAORMkjLL2w4k2CNGSr8dfbc7RLbIfDY+qvwDGe
            qBsrKde2HKBCC1J+6pTBfv+yWBgmLemyZD0lYPgEHjIOV2j0c1L0EsO2BknkQ//Z
            0274h13iNT+QztmcSMl5uTQ2oDVLbdOEqqLc8kJtAPvdtOJZz2R4Xfy0R9InOdmK
            qjpNeeo0rWouyyWwDNB/eQ5GxzKWS2Av9z/u6DXN195RWZ0Vd49DhuXtJxaFPl3z
            0Jmar7Yf9ZVBArd29gz8V9UZwsGDbKBZqtqE1E48J0yk4ddlKT0ZO2ro97+zu56U
            aREXY/QGMbNnNKwcVI5+P+FvCR0beNF8TXq5W7YXiCMogKdcy7GKfN/C3PkqU/Gy
            QND2qEtatBr81oTrCAJeYcCLzRDiwv0TP3HZCznNt3M+PjW9zvlleYiuQDkqYUcc
            XyvWLI4Jn7r4Rpe6CAjzWwaDO2lY1+AmxkjOMg0hawOXgffFd5toQBvvmZAUsLrh
            k5qp0dUJOYfUWxkUFUsCcRhFleba/gQfL+b7nl8IAytir0LTXDM98A86ziJz3aFl
            uM3buGYOwzdwI6APxhUFmYUkELcBwT0JDLNpP/2iVJNFuRL9SbmJlUpyWzBveZXS
            XAEvpIi+fMy+MexIvPAba6gWBN9wlwDWVXJNAeFpoi+IpFylqicPaXE2KQ/RiFBw
            SVGSZozZCLOU6yKGRJIQWklsT28skeAlsBSbMYqdAAFSTa+lrL9FZL0D8KTB
            =ILT9
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-03T22:12:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/6A8ryiPdzQlh72ACkmivLWtXy8ZXgHbL6ZjISWPDUYJR5
            nOaUr2fcnb2Kn5/6ZFB6I6kMEF3ngfblauYzJD9mBBN+DL4coMPqjCkQAqpEuBht
            +5VIlhue5ZpBMkLYh+boyDQPMYy8Gh7KU81L1FXr0hCe5W2E+2BOpKvf/VFZxfIA
            wN5QKbJpkX5BXym/y91butVQaV3HHS03JK20GzFUhcHs8Ef7ByEwox0yh+qiPo3Z
            NE0R5RJQ0UsTI6twMPGvKGwVh3SL4cplH4ExuPteyLFZPmyT2zmBEb9spMQ6QJmB
            ka0G1tGgwodsJbfFJaSpiYPiiSB0oxDb2D2C7uQvnXwUklCLBBWEnrESarmz6K88
            haaeINDAtXysackRyUdfIlDSVLXC5skccyRLXNgoaX12mwd7p0Bw3UIc4Aq5i3yX
            8XNeK0Qyy+8TYBsOntvmhskps5Uu/+inKS2oMihP9qY5p9nRMzVe29PZV+UULzXV
            QgRPOOpefqlSz7ve59Mc+JGAk4/6Kidq721J89CluNaplvCKFMvGQlB1zRKsR6XN
            +ouyp5qJbe0G3wmgwrAX/TNV6mirtTlrgEicxcb1lT/KlZ7TEkLdDNOPhSvkJwxv
            RPs6WCmSlThttsIgyOcfYa4V7v7JTnegNFPQiNZSiPrAw+mQFJ70VvnbrIsCWqfS
            XAHxlPABaCzNrqVF+7kAZmqvnoHeU3Is24SsmkFIsJRZLnWEoSFVjwK5JhoYrgJH
            6qirtelN1YwaUpKVm250CAoDy4T0Z0s7t9namQWTsHxifCIcvjWllLVTZlSI
            =2uH1
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
