# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MHVifGZ8WkdEQ2I0oKzQ,iv:52RPA61HJnGofAibB3cdTKTxPZQWt6aVIebe8LkAgUE=,tag:2V5ZkZmEPzFDkgb4xtSdPw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2ZdrCUL7IbRZusKov0xZOos=,iv:M9L8TXJaUe9xzZNXVD2n+E6VMph9i4mhFB1N524nLm4=,tag:1GMLIqUOCJqHd5ntT/22ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T22:41:17Z"
    mac: ENC[AES256_GCM,data:EgU3sFW/rc/yBP71wcS+qxjVFKUsHuAvdVcAn3wbH87BvFmyCxQGB/4NnruagwwfFfFxVokdPJQAlNcfeqwg6EYtoNXGNrW0SeEqVB5gZ6vMupuZd3aW0xBdjA39OZUuS4awk39xonLFrcr2Zwlo92U296NjHBcXnSyFrrU6lok=,iv:AFWr+MMYpDKpDYHrhiYf749GZw42TQpiK+qFFq5+0XE=,tag:3afou9LvTq2ZfyLt42T9RQ==,type:str]
    pgp:
        - created_at: "2021-11-08T22:41:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZARAAud0UVPYu2MVaCLLos8CKlhSGAfOKOKN/aTxnBxjRFrHl
            Y744YhwWa0rZkqmUxD3nm4/q2vQ9HxqesUc7z84R+4YIjUOaul7GO/HadhDvVkUF
            TLz2jDkgwk/yFMOprZzkLVxMZB2YSL0QXMmlc4RqC8YHitRGpabHqbQqhV7MvdN8
            GnjUfVsjUPN3CzP0cfqsmNy3PfT+2cJtkFGqegot9ouJ4qZajDzceLnttWH1wdgy
            U3Wfe8cq5CHDnpSvMXMozMBWS+bnOBL3emcsf+S3xTvpjRCUAs3BBLnYplp61Gcm
            wXv7PpFInImit9/ClrfJxon/8P9DeYjHIr8KtBJE+5yVyj73uY/j/SMM67DYxx6f
            z989evIaVbptD61sBZhf8GPewmEwWCIRh0ZR3+utpAooffS8GgNcgSShZ0ClN61q
            ulpTPCIKQHg+SqLioQrWdNHZnNOyfme9zn2ymM5Wv9hWaAIBlDobgJqTOcEu25iH
            7RanJB8v6HCiXEPXR1Wz3oreqoJMWjJg837WGKQhwsUgQ482NzZCSPaMnUh6SEkY
            xK8QWYnY10lRFEQy++a1dAtc9nA5dY60kQR8kDFr1DY9/c2niMxCzRqBUXwr2UwH
            oDCYuq24n2tCh6Hrzy+XGnQql7y07wjLgFgfb3hmtE1q7lRkcNxawKifUA/hZrTS
            XgF0VdETGJa7+y65fJ/OQjN2/P4bu5c7CPtvt8vo96ogXKeZtTl62l5OdhKNfLGR
            1ciEGRDnraT+O1arKVkgDkeUi+fOAopKT+eBxME9QQTdnRgzSAPW7JWEOGHXmQo=
            =jeG1
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-08T22:41:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/7B0/qPZpOsxqzRT2IFBO5EGzkeOROv/tdNhEITeJHrNeT
            dkQiO45X2+/wfI4D2KK1p7r/5u8USLs4FQicRNoQuX8ttZwY+5qox8g3ugz69hLQ
            uoSVKdRI7tYU/6F4JL7imUVcCEpYC4frp3VJHbX4tjjEoPZcEunG3uvqDBiqps82
            p01InS2XpA/BgU6gpGEw8IChymsvl8UVbkqXRUEBzFDoPVpPvNmdn/lNsy/+0BeW
            uV5TeApdBUR4M6A63eS+Ysde125aKFc4Mbb+eKEUMyceEReOB+o79QaKOw6Mx2eH
            FuUin3enE68i84ntafu/HsyjWBxKpXAqh0SqOsWJHVetO0QzMlAC5Zl3PsVw8IbY
            7GeWf8MUgGdlgGqoDiTCbYvcOaZ5aTFS6A5ljEavU2Y6tlkESxo7Ts4ndYaZjMTM
            TgWU8IuvMj0s+UYA5cQMBXubiyzvDfYw5IvFyYFaxtTjjPidkpcOffxeqJxrGL/K
            wrsSO3FD5DyMIGY/HKVQQGuyAGBuEfbcRLjMnxpDlQn9WSIzqJNd6fCF0ATXcLGY
            Pi22dO7RvxmDyaHxesDGSTccpZpNDvOfVrLEHIb13v9LGk3FD153QiifBAgJWAvh
            dKn7fhNaMcXGZyngluRjFLEuMuohEvz+iPE7VCieAf2vBwLBBK5eYsoUPb6GADDS
            XgGTN8guv2sj94EryzUxlfnd2e3VKfYozLd0DHlkp542LYbXqKWyxOmcVA8lVw8r
            XDsBix4FVcKB0SAG0vcazUkMSCMOzeeuyLNFB/R/hGZTf59aVYqeIs9qaS8m+io=
            =SO2r
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
