# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hLUV6lb6KAUhq8XrMYQh,iv:SScWmQmCteq+JdMJJHIDmM5sZ4k4XfCDTYXFe12Z1tw=,tag:Gx6vtfn0tiY7BVPClNWl7w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YnutCYiERrUQOza4rbsXGwA=,iv:hxopHw2Pue80CcK19PdB32uStgGSwf6DjjG/OFew/Vs=,tag:qMO6RDIEvHZmD7F8oVVe2w==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:5t0GHSZbenRcdzl+,iv:A3KVH5brrogr+scMlEUab1FIwvd/cMbIrbp6Cgb+24M=,tag:wYURa7MdhnG9S/CD6JelUw==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:ge5Gby3BUvWr2WjGhQ==,iv:puc4YK8rFMDor0C1JUG2Uoy2Yix1qFiDDKDHGtkYVYo=,tag:FVaf0hhTuWCckkWIlElKRQ==,type:str]
    SVC_UNIFI_CONTROLLER_ADDR: ENC[AES256_GCM,data:fslzggTjIl6zESN5QQ==,iv:BKLfZnY69Yyz7F0yU3MK5i1kGYMcRcEXk5QV6n+MrnE=,tag:ZBnlq4uu8QaFWFq7fz3xuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-12T18:11:22Z"
    mac: ENC[AES256_GCM,data:mmWQ8KJIoaNLUAA0PFDhFC2jvaqKhpGonb3/Lg736DPO6fgpDqRGcPHV+rnbFHXvGX4ayGBb5YW+GbGL5uNPT1Slupf+VPZK1epfipuzphvo2p35ScMczvMUc1M87CVT5mYgbfn8BOOKyFDBUi4uLG/R4GK1qtQEwYHRiEZTMYM=,iv:lKcv1M0/WEYPPAHjsPfm8BkUcxUi5Q/MyTI8d581es8=,tag:AGdhY3AbsfZ1e05yemMwuQ==,type:str]
    pgp:
        - created_at: "2021-11-12T18:11:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZARAAunN2oklhHfcOzKvP78ZxY+rZXkmgSGQEENgiXMYQHbFz
            mLphNzPiI2q8b+wWzvw9/xUS/QLP3aBP3YhS79pw/ecm6lbYAliBYpzJRpw4sUhI
            fGIrAmtMxO7A3DoPZb9FA1s60BdcXQHP9ju9i/Ei4DBKvpEU/DecVQcR9pKkuaLp
            PJFHgvuaXyvnSYjbv7McaurIUJbN9DfLFJypmsamN6/QCepXq1P8eW6xu7umNpDP
            erHvh1PMFKSbpld65t5f7tRUw5OgG3ZfO9pDlQWUOrObGFFMW25dAkL1HkgAuzxI
            dS3Lp28o/17FiWQh97+GFi6sk6YfYAt+MWkE9nunNFTSVBOO9M9gVXCY6YQOyW1t
            vgtL6IedxQnG2yfZUmkQPGLjuRIXie5uMePFkAr9df6yCkxuPhdrcQPiFKo4n6eZ
            UJRkJ+fKa+Ea0GNStXXUwgNwIJP0RADX4lfepxJ1u4QcuhRXj1jS/URW4CKbDNK/
            oBGDfpLib8m1B6mkrer6on6yESi7arT+Bi6G4JR3u6Z0QH0r7piwhRoDtoLlKDIL
            8kEpvfDKLaqX65vyYTY1RH+Dw9Xz+mm1ZXNpz9GtXMwcFwgO0gksWDL8sJDEegWt
            /KFV4Sa2gSevk850ln9o4c3EVBrLXipfcZkika5f+7htL5Gd4Gjw02uYiPGbsjPS
            XAHGvhnsa/8AqI/HhzSa2c3vYtB+21cJ70JAVeWwxUjZTCGZBr68CTmVRa4gfZMg
            lVRgVC0gNoJGjPAWms+5mxM/RY8TH3LoOz9aLx4r+8xK1Ed6mh0ggEiPKsL2
            =rlte
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-12T18:11:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gARAAgQuAcrODuwJoet8+7HJ1SWZlLHmHGewPoBoSv2wv0VL6
            A6QcGIpXxo8cRDQy8RYu+7XFTC45U820J/lvVXCl6WQtG1NijEA2ybyFVR8k1Xwi
            7a/rv0D5tBlTkeieRWOKjB9dezG2byoqO+T1NMcFsKmUkK/C4qMT6B2AYg5uu3Zs
            cwmMHgJ2cPUiBbkh9vmo4Zjx3+mcBRSJUiK2bus7AIxCBMy7TRPdJLbao0E59S8s
            zbQAxvIEAcHnsKVs6/F9lcdstUosMH5e2fzRHPZoPaOL3dadjTC/T/PIAUdh/qNs
            t07A6Q12UYCLmBE2ewRGf0Q0HfisYh7NveMHh9K/GdJ0VInZI4zt+dyLSWXKlx0W
            m7WD+vgUSw38M44wcLT8z2rjnHJ1Ea8ol3ZbwpD8u+TuctE58MmrodWhQM3TIwdr
            q0UPMcvFiNSamxLpgjfrvk7cbP8m0IcHq3A1U23lVm0NsSODAk9r+yHJEih0mPEB
            y5sednT5FlmjvI8lpLT4A9nlvKNkhw7I0csLy3KWD2gH+JH0Ci8Hbmq6gABi8nks
            yBjgbH3HcFKwolVsue+BdSqEfBuh9mjpKfpim5vIpQna5+zW7w/SbGLR1b6jSY1+
            GMXKR4rWy0aNRUvWNtFV55J5bjZD/5P4Uy3VhdGCE9tDCKZYRpn5Vcjx3kLs+Z7S
            XAGgsJafJZft3TqIIaeR+QkKDG5aA4dpCWldaN61UYkFtMocc8hdz0W1d2+Ai51g
            RFoxPE4VmCz7VK/xap/Ndo9/fd7L9OlRqqHrRl8/H3LNeOyAVqN2dhXGTC/v
            =4yeL
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
