---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.5.200-192.168.5.230
  METALLB_TRAEFIK_ADDR: 192.168.5.220
  METALLB_TRAEFIK_PUBLIC_ADDR: 192.168.5.222
