# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yFygxnZptY3WJpPOnyGK,iv:0mqqz0drJF89uj8CpXpcnjiZt+NNzKNnGijFemBB67o=,tag:SrDnTmomey/imKbgCfbd8A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nCVeKwE8RhzeaMq4b7cfoVw=,iv:kRuWCWBPhMqLDF5cVB6qxhlMmxQlQ+PM7bZz1/ZJqjs=,tag:uer9+vCb0X5ilEI+9WzVdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T19:06:45Z"
    mac: ENC[AES256_GCM,data:5SdDl6aRsKDaBXUgA7nqbKSXWJnLGeon3DZ9aHxYpzv1f//KsphnjLxlf5GSbUaAdY5OEOArTdH094uJVoOcaNrxOdGp64okgUnAKkaPVJbAbr3ptLrF2YBsv1qYe9xIWsZg8mTO4GJx9keco75vRrhGj5UKpdBFH0JbTnFmoU8=,iv:qLPBKNTnWfrkE/R+XT6TaP2ZcHESXQ9LsHalV9qubcE=,tag:P/FfZ6RCvSW6F6DUpmz0tQ==,type:str]
    pgp:
        - created_at: "2021-11-08T19:06:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ//eNK1uQEhuHrfx62uj+5BXv3XkhBqx7NhBk5X5wy0Fdn+
            gVrjzimyu3m92ikFKOJOnczoxIg/j/eDE61YeWkMq+aG+06LcZOT+hp+ZU0cbcwr
            3rMoUy4ckBUpc6zPuo07ZUmIkKyFKc2RoSoDURy8dH0SEQ9uR4ZDqtDxF/Lx1CA7
            Vnt493IPWeEToI3J4ldnUOFKjAmYgIAU5uykJfsILyG6iW7FU/UhQ75Nm2kr/YC9
            hrQVzk0A6uZGlYtiKUB2aabi8d4V8nmaZVrwfdjyJ7UeDtGsctL2cKbxCC6YW30Z
            Z5/btvbDo5426bmCh0shmAV2JAykhrYFhjJamscgWzDfoTxslsmD3cpaS+Uu3SUq
            NrBz7xqn8PFDieUJCBWltxkZkCFv4Z1t1gUm/6HZr2Oh9hrzfm7cp6cvDc9hCLpz
            lKj+5HK8D6z8pfvtg2ut5r4aE0CD+PEkwLlTS3b0Ww6j7GU38h8MxjldeLAnKzlg
            HkuXZoq61184QiqdSSRIm0bjb1z0Pir/xljOGtTLZv8frYPoXzmVJKTELftOYAME
            CD8IrYL2az0HRryB18MqaWVyVse74P4LJhyxNbFk32gdmaNsQ+AII5gHPz6SQWjX
            UQ943ams510kUCNysnYy/NpvmO6MkCjW2Yo1HOz7tWDjSdu/H1UgNNYWesRXEZjS
            XAGWDR0+EmfcTneIUkDtu03447LPIPLnxTIXqRp0a5nayfdQ4DyY9U/U4yfmh+oi
            5hkDDlHjD2w92A6wTTVb2S2j7vwHn1XnbQ7GtFfqtp7u1lHEvXxH57ljU0t3
            =LYqp
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-08T19:06:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gARAAkBh090Pu9P3luxrSH/9w9WaZczafACQEBMi8Dlmx6ptB
            bJaUzJr9cr5uDW4WOf2W19ksSf7w1NXaVKzvY8IfH0MClFJxKNkBK9DNwW1SxZKi
            5phwx4paKFOh1ogTZDiv2SpYQNjVBLO3sRewZsnpehZaUFbJfbgWdOr4w6yx3o9l
            XHtv8i2sAOzjsmlA/cXDyHKGLOa3uT/EZPets5UL3NQARVPIvHGZBubK1bodxmpv
            09pjziJ3cZ5Bkzku/CpeHdEVuXCs8zjbZgTJJDUnfO4R3kd3rC3Dr7BvxsZt2e36
            8hyXUeeG4tw4nmcaLiVXH88Y3popBUEfJJxXNRlR5wM8sTrSQmsVqFJxZO5NiWRR
            4GYdBwjBdAcLgI2Ea4Rv91NX/7zlodylRa4GkPg5VNBvII/3f9H5RRRnHe4pQ3ki
            CTVb6sMk7rK0sVY6G0JmO0VLVRRreWY/hdqfEFMlmO1qsA3H+5mCS21hUtGppEUY
            W2W89vzLAPLQ9SxPgRU37cWwxeF30+JvZYQwFi+tYmCGBen5F6yczKyAl2HlvGoe
            7kVW/QRsHFx17e1P6ofYbAXfpRiVGQDcQBUmM6AUToEQOj3mr9rPUvmkzvjjNAsN
            Q5+AXj+ENY5YfEvhQOAHH3mKedfA3YdzoRqcp2aR9+7AmjxI0dMHY3iuU9le1bfS
            XAFnDxVTwGcQ6CS0rlwQwkwnRLUrbFJO/MEH9kY4Pj0ycHUfPMtjuExIQAMyEUUD
            Z/XHn7DGt0M6zzNyrhkz8j2JPcsOEsuoaxNOZCugLH1D6+t7wIJIvuemOgIu
            =ee40
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
