# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: null
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YlLhVlYuIJb7HUMLwhYMRng=,iv:UmobxGldtXcSN3tBfySk7PcaYpaBHgYzVbYINzBKCBo=,tag:Td7COg1rRg1+zx6AywXd4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-02T22:16:37Z"
    mac: ENC[AES256_GCM,data:It2xh0bWX++ixAtMQ2Ho9RA4/Hu3M1wM6gz/5+qk+wwCT5wzSiqMivCMxDzNF32A7i9zgO0OlRRCj0PpILwv0Iond9q10kC+xFqMuxp/RXfoGKmmPZZDIvhpocilOhUmBDEDUVhNCQKmRVXzuhhwPOWkBvljm6ATEr4AzmkJJV8=,iv:Q9hdqgvZ1R5XWHh5QozHcrIa/TsqX28qNSW/1wUXd4A=,tag:olfuUDMgW3NJXUSrXPlvRA==,type:str]
    pgp:
        - created_at: "2021-11-02T22:16:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZARAArx9yfCYvlyfLRcKRFLLzLulWC3I2FpBZnOucHxWwUFTB
            4EV5S+IrcHXdBlwQQuzXx0ygAr3ZUcrBZBXBcybS5dYvHJ+03gvTwZ3SDhYgBTeq
            Mjs/nGLZzuIG2We6TGwHcVtX5kv56J2jRWplBRW5Y/i+3NzOzi2z5ez8uM11gcyF
            sjtfv6MF443UDf4B4V5E2q+jCp4Hs+391ghiBGGXMv2H588TU8x3IrgYpeLxLfpE
            N436Ep4RDaF0oTliuzQyi3+PSZb/suQuc/5FvSnFLNf7SnSF00erp/QGArxwC1ut
            km77VC4A8ioHKiOHmY9Nsn1NDCTqCPDdFB18tLQey4xykLZXLh1UEYmIvo4iQEbl
            8eBgh8a+WkGyCzo0uX34lBBlI5KOPUvFMohWEauhuS/VULwZ/VKLmhllZCqRxloP
            Z5QjP6QJsBoEqeCrlgUFkJf/q0Yf5cmpS+D6YkoHAOx6smZ7NcZN60aaP1TzYPWk
            6oEzKscW/Cenx2sYM0zOLqzquoBlDwSUKqd4jUNgMVpSGQ5xPw80gPVlj3H3FdbO
            dCw7yiWeGBXYKEBuuNXg4RziGru7wWEHydGch37HPWhNZoILB5b9zX6Fu0FGyYQf
            +PKIy76FFLWkUvBmOnz9VyYNSsYcB8glBDvKI/HgORxye3gx4nwhERe44iQk47TS
            XgHZfcDYbHpBZx3YLwCNlQyDt9U/VbZ33ZaHHgpnGPY/uRRB2Z6Gy2s780Dq1o71
            dbcxsP1lIMt7VTTmNlnMy7N2b0VLZ43CowtHPiyMQKNsjJO5Z1gUed940a1Cyc0=
            =C1De
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-02T22:16:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ/8DrJMoLiW+NA/hsgBnB47IgHc3ZKS+X6ESCC3SS1BNa86
            9OT1koGd9/o7gM4M/6qIpsg6vvBEBKlrNlMpq5tHib7jbRVfAJxmBBrZGs4uihyc
            gVQiAFcvgHIoL2tD8Kp2hlow3GenvGdZMPtHwVO/TeXTwhzfhhtOyqaTJtCpYiTZ
            BeDeG+SJvF1WFHqZ/76A+N3Qrle0WIvs6qSOk0ITzKM+fu1ttXiBiI77VsQIESAn
            LU4FPYv4F5LAFyqiCExbgm+BwYoDBB3wC5XmS6lPniM2De/OXnQR/AeNPirmTbwg
            uwK6Vkyi+gvJx0htPa+JQhKjC0pR6Csr7CU8L+vJsbMsWjT5aR4RIrohoOZRWy/h
            JvTMZ+5xTBugS9jSum4RQIpvMbyhS4Iw5KZcSLK/M9vHJZoEwJaUveJJF9yiSGCB
            3Luf3aDl6ZMOs6Bonvs4Gnx+6w1j1Bxl51loiyXNANQIzOL0gRyO+J5g3Cgf05qO
            0Yf+cHE48XxY7qglLjzxhZIQlO4CbVP0ePtBmDbyY5rfr4O9BUMDb0IIxA2zBzwN
            SauI4TYcXE55CtBeKQo41NMf/hoKpQKhxYj+AcP05zFwL5V7l7Vvrx48qbAHYxRi
            W+lfjnQqVTJBA1CcIbf37sAzpn1OxGMNt3E5Ikr4hKtBk120kdLhE/tJlFtf+6vS
            XgH4yZ85mW92/ipuEVLzWYMZJCpMJ2QLim10jqqYCe/IN7CDJ606BGdLILYwJUtH
            P/udGVyhd6foVF0fWlhGP2YboH1BjzPTOfscqzT+5YSgdfsXCvs2/hvsmPUJO+o=
            =4ABv
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
