---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr-nightly
      tag: v0.3.0.1745
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: 'true'
          hajimari.io/icon: cloud-search
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
        hosts:
          - host: prowlarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - prowlarr.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 100m
    #   limits:
    #     memory: 500Mi
