---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      nodeSelector:
        node-role.kubernetes.io/worker: 'true'
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
