---
- name: Setup NFS server config
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      # SSD storage
      /storage-fast 192.168.5.1/24(rw,sync,no_subtree_check,no_root_squash)
      # General storage
      /storage 192.168.5.1/24(rw,sync,no_subtree_check,no_root_squash)
  register: nfs_server_config

# TODO: Clean this up
# - name: Mount fast storage SSD
#   mkdir /storage-fast
#   mount -U 81fef8f6-d48a-487a-b92f-10c01447fb2e /storage-fast
#   echo "UUID=81fef8f6-d48a-487a-b92f-10c01447fb2e /storage-fast ext4 defaults 0 0" >> /etc/fstab
