---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: nfs-client-fast
