apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: tools
stringData:
    authentik_secret_key: ENC[AES256_GCM,data:LR00I0IVGDD+pUXGeEcWBx4DKz3hJDExPcHSsKLieUyllNX8VH47nliuO28MrKzP,iv:ygsiS193S3yZh513XokdfyE3y2RJCxUD6DsqC4nNXaw=,tag:SGyahSiYzslgjg+YI+0vfg==,type:str]
    postgresql_password: ENC[AES256_GCM,data:g+/O7n0uD2UC4htqbVd2L2fosuwn7MKu,iv:rbgGxvE+j6G1yd4msISxdPVU4zkZDc+/TTg8D2Z/Rcw=,tag:e7hAGIxg666ffZ2aLhgjOg==,type:str]
    redis_password: ENC[AES256_GCM,data:JVdd207/O8pif/LpGApZtMKIuu80Vzn5,iv:Eg3DDm9AIhvCch8zZq8sOmN2et6H1AjsACYxT8UdKHE=,tag:Wrj72IO1NCq1uCSPJTPTSQ==,type:str]
    smtp_host: null
    smtp_user: null
    smtp_password: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSE93bXRKTVllN1lTbzhm
            T3piL0l4YzdmbjEraXBCKzhHUlRhSERDQ1g4CnRSZnlHMkJVUkdVc3huOGY5V2NQ
            Y21LVFhUZEw2bnJucDY3eFUrelhjaE0KLS0tIHQyNzhqdmNXWFRYdWlZUUdOcHhQ
            bnhyOE5wc1Y1UzdkMlZ0MjJyWG1qUUEKDI02qukc8micfAfM6tG6Hgv5wPXgO6iu
            oVzCx6SscWi8KRHgU7p1WCb2S1FOkWYaPsrE4LOMIn+TqBqHyONXpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T04:05:03Z"
    mac: ENC[AES256_GCM,data:lqN+GseIkNVZbfRrIXoMT4gmvTNkUsiMfe+oJsp3klW9habcXiIM7F/q9uQ6wWuAAwEFU/NtlZQLiMPfvM9w/BYzA8UojI4bS2h9PBluWeNkuSKpSfd+irAsyokd9Pg1SjF01gIeGde6S2PB7oQ0dUv2Q6rXaB+dzDoX7c1gW9w=,iv:7OhLut7JKG49SnGXhwU6YmgXpoSrPwBPMtGl4RkNLvI=,tag:hOSH8builz3RoMfAUXEtuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
