# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick
    namespace: falco-system
type: Opaque
stringData:
    DISCORD_WEBHOOKURL: ENC[AES256_GCM,data:Qg6G2SmFdByJpE0t8r/4kt2bso1huYXq1joKNJ2xJ5Ph+APuK2wDmpc3XSG6ZjUnAqcBxD3EE4OPt0DfizKJ4T+ab2HwdeH7aeEVVUYSXzWxdA5cZYw5eF/m4fCI14k5hYCvHosFKSevtqRErG2ZBTzdjsRin+roIrVa,iv:yS2Mf1VVNpqAQ4AK/OriyqwLQs+3nw39C1ZsO4f3YLI=,tag:nLOctb3Y9t/BwxMVlmFjYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SE9lL0ZxTDlMK1FXWU5y
            aUlLdTdlekZ6aTlJS2hwdGdteEZyQ0poMERVClIzZXE3MVJMV0tWR3VidVR4ODJT
            OE51WE40M0dGSXFMa0F5MHZZV2dvMUkKLS0tIGNhM005N2hiN1hoaGpRazVvSHpC
            dWIyVlBIMjFPNEYwcU12bC90UlpiSVEKKu0JCYal1iKBPBpF5GqM3WJ2m8GlTsnd
            YII7ZHovF3Q21n4mpp0SWe4HfZuDRSLciQv+S9b5UM51I0aaGZNVSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:31:10Z"
    mac: ENC[AES256_GCM,data:04G5B/cS3XxV16nCwXojfxeLFK3VPLKWgOth1ABM7t0BSyAvpmNdk4fC+aSq1YbWiun/bqg+7iSZFExUF+cJco+Ma3Q9+lqe1mfXsvF8gpFA54sjU/S1BvXqS2fNO3UbsUdQ9JoM0NuPyzvpRR1gfllatvFv/DDoLbPe9HiwloY=,iv:bQlbw5qAHAQFffBC/Z6yZEktFmFB5nWNoOQICLtI9nI=,tag:YAG7RMYvwaU0HToAPr80TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
