---
- name: Create watchtower directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ apps_dir }}/watchtower"

- name: Copy watchtower docker compose file
  ansible.builtin.template:
    src: watchtower/docker-compose.yml.j2
    dest: "{{ apps_dir }}/watchtower/docker-compose.yml"
    mode: 0755
  register: compose

- name: Create watchtower systemd file
  ansible.builtin.template:
    src: "docker-compose@.service.j2"
    dest: "/etc/systemd/system/docker-compose@watchtower.service"
    mode: 0644
  register: systemd

- name: Start and enable watchtower
  ansible.builtin.systemd:
    name: "docker-compose@watchtower.service"
    state: restarted
    enabled: true
    daemon_reload: true
  when: compose.changed or systemd.changed
