---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tor-relay
  namespace: tor
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: harbor.${SECRET_DOMAIN}/library/tor-bridge
      tag: latest
      pullPolicy: Always
    nameOverride: tor-relay
    persistence:
      config:
        enabled: true
        mountPath: /var/lib/tor
        storageClass: nfs-client
        retain: true
    env:
      EMAIL: ${SECRET_CLOUDFLARE_EMAIL}
      OR_PORT: 45532
      PT_PORT: 58283
    service:
      main:
        enabled: false
    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 20m
    #   limits:
    #     memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
    podSecurityContext:
      runAsUser: 101
      runAsGroup: 101
      fsGroup: 101
    initContainers:
      update-volume-permission:
        image: busybox
        command: ["sh", "-c", "chown -R 101:101 /var/lib/tor"]
        volumeMounts:
        - name: config
          mountPath: /var/lib/tor
        securityContext:
          runAsUser: 0
