---
- name: Add aliases
  ansible.builtin.blockinfile:
    path: /etc/profile.d/00-aliases.sh
    create: true
    mode: 0644
    block: |
      alias k='kubectl'
      complete -F __start_kubectl k
      alias ..='cd ..'
