---
- name: Check bash-completion is installed
  package:
    name: bash-completion
    state: present
  check_mode: true

- name: Add kubectl bash completion
  ansible.builtin.shell: "kubectl completion bash >/etc/bash_completion.d/kubectl"

- name: Add aliases
  ansible.builtin.blockinfile:
    path: /etc/profile.d/00-aliases.sh
    create: true
    mode: 0644
    block: |
      alias k='kubectl'
      alias ..='cd ..'
