# run a weekly cron to cleanup freespace for the lvm thin provisioned disks
- name: Run fstrim every week
  ansible.builtin.cron:
    name: "daily fstrim"
    special_time: daily
    job: "fstrim -v /"
    user: root
