---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.14.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      name: ghcr.io/k8s-at-home/traefik
    deployment:
      kind: Deployment
      replicas: 2
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: ${METALLB_TRAEFIK_ADDR}
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - --api.insecure=true
      - --serverstransport.insecureskipverify=true
      - --providers.kubernetesingress.ingressclass=traefik
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
    additionalArguments:
      - --providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_ADDR}
      - --providers.kubernetesingress.allowexternalnameservices=true
      - --providers.kubernetescrd.allowexternalnameservices=true
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: default
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: false
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 100m
