apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - falco-system
  - goldilocks
  - keycloak
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - tools
  - tor-relay
