apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  # TODO: temp disable until we get resourcing under control, MAN it eats the RAM
  # - falco-system
  - flux-system-addons
  - goldilocks
  - keycloak
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - tools
  # TODO: figure out port forwarding issue preventing this running on k8s
  # - tor-relay
