---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - cert-manager-dashboard
  - default
  # TODO: temp disable until we get resourcing under control, MAN it eats the RAM
  # - falco-system
  - flux-system-addons
  - goldilocks
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - tools
