---
- include_tasks: apt-sources.yml
  tags:
    - apt-sources

- include_tasks: packages.yml
  tags:
    - packages

- include_tasks: filesystem.yml
  tags:
    - filesystem

# TODO: Enabling IOMMU breaks networking stack in Proxmox, need to research
# - include_tasks: iommu-passthrough.yml
#   tags:
#     - iommu

- include_tasks: nfs-server.yml
  tags:
    - nfs-server

- include_tasks: preferences.yml
  tags:
    - preferences

- include_tasks: ups.yaml
  tags:
    - ups

- include_tasks: aliases.yml
  tags:
    - aliases

- include_tasks: backup.yml
  tags:
    - backup

- include_tasks: postfix.yml
  tags:
    - postfix

- include_tasks: qm_restart_cron.yml
  tags:
    - qm_restart_cron
