---
- name: Enable Bash completion case insensitivy
  ansible.builtin.blockinfile:
    path: /etc/inputrc
    insertafter: EOF
    block: |
      set completion-ignore-case on

# https://johnscs.com/remove-proxmox51-subscription-notice/
- name: Remove Proxmox nag
  ansible.builtin.command: |
    sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
  register: nag_removed

- name: Restart PVEProxy
  ansible.builtin.command: 'systemctl restart pveproxy.service'
  when: nag_removed.changed
