---
apt_install_packages:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - ebtables
  - gdisk
  - hdparm
  - htop
  - iputils-ping
  - ipvsadm
  - lvm2
  - net-tools
  - nfs-common
  - nano
  - ntpdate
  - nvme-cli
  - open-iscsi
  - psmisc
  - qemu-guest-agent
  - smartmontools
  - socat
  - software-properties-common
  - unattended-upgrades
  - unzip

apt_remove_packages:
  - apparmor
  - apport
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
