---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cloudflare
  namespace: networking
spec:
  chain:
    middlewares:
      - name: cloudflare-ips
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      []
