---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
    env:
      TZ: America/Chicago
      DATA_FOLDER: config
      WEBSOCKET_ENABLED: 'true'
      # SIGNUPS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: https://vw.${SECRET_DOMAIN}
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: adminToken
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: 'true'
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare@kubernetescrd
        hosts:
          - host: vw.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - vw.${SECRET_DOMAIN}
            secretName: vaultwarden-tls
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    # TODO: yeah it's not using postgres, should eventually migrate
    # postgresql:
    #   enabled: true
    #   postgresqlUsername: vaultwarden
    #   postgresqlPassword: ${SECRET_VAULTWARDEN_DB_PASSWORD}
    #   postgresqlDatabase: vaultwarden
    #   persistence:
    #     enabled: true
    #     existingClaim: vaultwarden-postgresql
    securityContext:
      allowPrivilegeEscalation: false
