---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-postgresql
  namespace: tools
spec:
  storageClassName: nfs-client-fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
