---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: tools
spec:
  storageClassName: nfs-client-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
