# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: tools
type: Opaque
stringData:
    # TODO: gotta change this woops
    adminToken: temporary-token
