---
collections:
  - name: community.docker
    version: 2.7.0
  - name: community.general
    version: 5.3.0
  - name: community.sops
    version: 1.2.3
  - name: ansible.posix
    version: 1.4.0
roles:
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.2.4
  - src: xanmanning.k3s
    version: v3.2.0
