# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+AYeqzp8eEt4VIj40XlhVhOKAs36n5M8pecU7u2yZtXrWSBS1w==,iv:ED+J/dEW3rWYfepGrJmmUibQftFLRAA/Tm1VtRAwFh8=,tag:qYM4yvPQ1DqhVMhlQYV19g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-03T22:12:06Z"
    mac: ENC[AES256_GCM,data:nj2pQO6gdeKesFNdJm1QJFq8HLO06j/2UOLCXzhb69DIM+xVDItpJO5qJfQ9PUEn19rGPatsTApEs/j/qBZbINjEH4bw8W6/E9mOCMMKRZ33bQTrVlJxo/MEk/xQPJmWtWvQZ+1cPONwxSPWOmxaK7+NcMyZT1mGq4ZhAYW7NSc=,iv:hZ9sO8FgLEm+hLDZq0MIC8YRK4Sie6hwOx6fv1t1w1g=,tag:guwaBMFAxEGbvZvjlOoLoA==,type:str]
    pgp:
        - created_at: "2021-11-03T22:12:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ/8DHRIoavgQ3qQXFZeqixTaN88h1k8T4811MxA9fXm2y5R
            msaYufDeWRXxhviW4KMaUbZTb+VZJrK+EjaK80yU7wk6MLBRZktsZXeShEvQ1Gyp
            eIDTd9KCgvoYgvUhtOvPU9lixD+EH2q6868W62mCH8kP7ustjMy1SBNDm7q0U0en
            ZbfGHbC1nqHxBHktdAlMF9m1hI2CoeG4B0lns2LAhyxpdlA7f7sb1PB0/NxaSUQs
            8zgk6qijOWFi9LQCS8e2FC1cbU0Vw4ZqUdyM9WueV3IcWzlofM0ZC2WWn2IejPpd
            0V7eSQv7Mt6LTBkqrq+UQ6vWitQv9UiSa42Iy8YVsrjQEBsuGr/wk9hn9YXhebQB
            sBJLKwM1phmuj1T5Mct3it8AA4cVKlx6ZhWjWrUiWW98tuNpJqppwMrTTIyDPfn/
            3HKaTB4IrNoBRHeEXQ2KqWRn6vjLdIjRfd/cDGYeemFS08zSXj+dEpmk75VUo2d/
            t3gs6cK96fp++XbhX5mnUjYhhq7h1JVakdonWVe3rFylpFGvPYl+wKAqoeurWOHe
            2rqSxkKEgVqcGNwaBo8wEAPLkBYqYYvfyctSsNL8KPh9dShsf6uq0Z2kErAoNnZO
            eFjSWH1I1Ic70hUtCFWQOHW/jI9KxOfcw5xAv3hqTDZ4oUvLry3SEgmUj17r7OjS
            XgG+zYy+MHea72fMTorVdKiQwgJyC+T66vXbu8h/z+UP+0cMJgxs3rHheoxhf+Dq
            JoCiKGNkxTcY/q7BAQvuTpe89LPcQgYM6lycCoBZD1d2z5Ed6KpcmrZYkDLegrQ=
            =ejF0
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-03T22:12:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ//X74/QCBZkrsiuBho/rlYxWx/w6WCv9U1oiDpLhjbQnK9
            2rRathIpgziG5/U1uC/o2X1x1bcG8CHOAJfhZXHwmBnNjLa0ufc1cxRpXEfvFaoR
            cUdHDxEjxrchwcT4pm03gbj8V36fQac5aYzT83B7D7ExvyPlEXXNqW40e7UeG9sr
            kNQgVg9o3jSrviu4A+0gA6XUx85kv149+F9Y0M2fafGez2QhFWjmFD0K2HmgLKaS
            35m9bqcjC+QXbK3NHCFxdFZ/hL/iK3h45iRtU2Rw56cnDBDXgnUtd4oDDlRyCAWG
            dFBNIEjQsivgG92rOFvLe8sp2EdRb5+kkzzgjhek3aqme9Sngb7VzQcXZrMHiaUs
            n0MnmO0SrklU+lPyH0mepVkWMoMRO3TB37aNADdRJyzDuu+QvVJEhpZwpDd+Duzv
            dchSkcph6TzF4GNZM7/NgkxDbp7jGSYonoQEgkwnVwWJr31gYCT+Yvz2Quxwk1UL
            Q4fK+NYpoo/2uysV98P4TMp35QY7viq0ATWzZvHQKucQ12MQFPW5um7WNvg2ui9y
            xXoLoAuiQJ7qk8kxFmOpnKWc5/Gs/49GuRkOAO8a4Fj/bu6uBgdnjUu+Uee+2eOj
            hTU7vMw6RDgujX1LWgcm1Muw8negrq5f61FACVvWCuvAGhoBx6SYwNPffZafijHS
            XgF7zqmGkkkYzbOXn6dA9X05lsvdqklUF9zqgDL3TX76cnfUDBRR+5bnXBnpiE2h
            BnCAvFQYn5MY4RcjfswY1K53cCJLZg176Z8eQuT5x3NVLSCk6g6iJuSctsIrGFg=
            =NyW2
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
