# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:JY0YMYss3t1LpZ+lcZ/+oKPVTpsvsOAhUI/6NJn2RFdePBp0Og==,iv:Oz23dMTEQiMEqljQ04uX0so3vLHX/xtS6HesAWRr538=,tag:0KjLMahxDFmO24HY/XqOmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-02T22:16:38Z"
    mac: ENC[AES256_GCM,data:Msm6r+T2OMkjmAdZuUE4EZYIacASqb8Po/DjPO/wx8u3MQyfaRIqvljL3uXYRfl0M1/qA9LziNW6nMItV7WJUheMx9mLY5W7x/H7P+RTyxhdRC5MEZyJb1+LnT6XVyKjr9RzSXZY+5vt8M/ojLfjJEFzdYGxjrJC3DW/FbzvPR8=,iv:fbxqZCVr/Gw8WXlqF0t5f1DNksawKqUPBb/LO2I1dMc=,tag:ZMAsEsaN01cl3k9UyYLBgg==,type:str]
    pgp:
        - created_at: "2021-11-02T22:16:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Mj2VqrQAGZAQ/8DpvsrhGYV/JAwWnuQAT76peApiW3kNRP9uKhQXg+3Eet
            WE0Ua4pDpME033E+md5hcK96jYKOz5eTbWV8W48ZV4r37nsJ9POXLz+rnOi2oUS7
            x1whXH+8qM7xsWX1o8+h8uZATGvigwZZ/+zCQPTPWNQ34gmEARpQuzJjDTWnH2VM
            GIuLK3JLAKm1tRnw2f907Q0ah4YUFIQIhhMnJqzdCo6vmntCoW2fZBqq1/MbBpvR
            0qFl//pDSvZ0IHqcQJXmHLOFnxIZGfqh2ireipGZ+spOZLtTLPlRqAUSdt/EnaNd
            d09nLmu3tj3eKFmjyWYe03zcqMTIoIU5nqxhT6R7YidvDW+PpqiDlisTzjKEO10w
            Xner6FcFZ7IBy92LOTX8G1TIZFPK3O4vT9YG1nfeyD3KiyIRH+RUFa+kfHPus9Wm
            lGHeWlwi1LEvA3WIt3fj+aSOdFSIy1cn2igv3eUK4JYLctHNhpNqA6JKsJiwcanT
            ND3aJLBKbbi9xnDzRJRL8FVydsY8IdxEFpb0Vq2cI6POZVrQo1Zuv4KfCOl4LmLr
            /X15/3atGR6/VmhKwseYzYdX75uF7+H1dRo03PdYWtP6hFpffjLvZ0Qzndem8khY
            MuraabrxrFlnrdvxpFZnYgweYyl4kgyWB7Ylkt+VPOMO2Cm9db7uDAnCNyRe+IjS
            XgHo8KswkZPgo3DljAVkqUflKfSjPV4sRSdxXPjBskn0PMhlstpL/KxKZjbA7REe
            GI44jztM4kCbHyLHNSt1Qq+quTp2KL4xtehCAlNw+Tyq9K18kAmFAKj3QI8I8AA=
            =Y+k2
            -----END PGP MESSAGE-----
          fp: E9980CF8F7EFC7C0FD88C4A3FA6A39C8AD70749E
        - created_at: "2021-11-02T22:16:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KZz9vsP/8gAQ//e2kydjEsz4+lEhxuoGH0SKYbMvuUNdS9Jqigq/OjN3yz
            3ic5JYXiL3kmEf7OED4I9v1hmB4ECaNPQxSVnjqPgx3GUnL0K5z18eofA8Bu47PV
            ALGVspBTsm8JRllgHu7TV0GOlUBcbvfbz40UniUcYe+DLz8ffWaBoOgAK3JdQ3cT
            jrLiOYWtOaJwECMJjc8SkcZ3GawUEccsKImg2liBa6KNKeovwwTy7EKFC95Fnq0O
            9zRIz1g1AlmqhWas6dIA2RWWZ6vgv3adDDcGHUoQVSQm0KVc+ldzTsIro1kEh5VS
            dMBst3VDDFyOukFvghZ4O5xTHd8UVCp2hkxgh+NcXEROiyhy6knN2h+Y9IkZJLIW
            zP7UMDbf3vsWMgCo1th7JyGs7CxZDQGSqOulU9hYmgKuqzusI0lkIP2rRGsMzL49
            Yb0HpI9t7i6PAtVwFJJFLgdodnMgsaaJCfgu/0yxmQ5lC3t3blIUa1ONSbFscqC/
            oxTLW4S88mxvwDA5bqtB9J/dUJiCSOLjeyo+Hatlk9ckPzECXHz9Hm0BaRuhkcId
            o40IgJItWYz13GeUkUYmgD9bmTzypvF2E2zo0qd595ZK+0E2LEdCMvudx6W0FISJ
            HPDmy64s+M4RXB5DF2oNvR5yEvrVSW1hXkvFd68GEge3qoGBHAW9JGhmywwB2MXS
            XgHrAyPunx23Y3IWuSm473VuruEHafUaRvprjxngq8tjPzi/p2kRNqTKI2UxjxtK
            8ovimTztpFmCQkXhV7PyBRDN07Ed/1hMtEl7D6EkFsgemFYdWo3BWWHEkY1dIjA=
            =6v1/
            -----END PGP MESSAGE-----
          fp: C88417305ABC754008D7311011E76188EA3899A8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
