# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:eKND7jr4YaGTsp19X1N7iinFE7cu30/nxHFkvc5X1uvu0/+fyA==,iv:v4v2UiGboCv+897x5MVPwTBzhnCy93DOxRxIHtxdKKc=,tag:poafPu61fSM7TRUhWjVOFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNWpIODJmdE9XTFNhUlhK
            dEYrcUlMa0dxOTg2dlRNRHNTN1haY2pibml3CnBTajlsY1JuL05tUVByTHFaK29T
            cVhrZzljSXdOWkxmSEZ4cHpYUThVOVUKLS0tIDYrTHBHZ2JkRDBmaVpMWVloNVhy
            dmdSUy81VUtrclNubEErSXU3UGhuVncKGl/5hlRDNtmbeH+gtNO0u5KX1IooO9sC
            5Ta2UJyPRX0nz+MZdANa5IvriBlhNrWXOy4nI8y5KWrR57kJ0HzA0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:z2b2dI5p/SYyH4p6hAD7KlULRKRgVUI+YT3oo0q5/9OG8CmKKNkGtFcYtj2UNGTxiBsERHflSNYQVsBX6FkiqWfs1dW7T9rz2IaC4w7avLEL1fTwc47zwSZazAQdhNRgwp5K9NNg8H09RfvSSA0xEg1ijo5kpfTKbuoAuTMmnzs=,iv:wnGpwd9qqIstT1wJVHokUfSQZ8JFKObcnXjOPsJMrVE=,tag:iWjXroICC40vtVewqgQPWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
