# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Ak4jRqtKvWB+6Tk0zr9VDpeoQMF0nszVuLUDhg6H8FQ2TEeT/A==,iv:19JJ6S6EFlbfv8dGAUDP/tm7b3EnBnzL8kqJ3kU5aao=,tag:JpeatGMriTqcIJC5hbmE7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VkFKd2FNWk1sNVkvRTdV
            ck9KM0taTUJ4WThrZVlCM2UyY2tuME1DK2xjCkJFMnZYQnptSHFWTHNHZFZUc3RI
            OHE3OU5WVjZERGQ1MUJuQ0NwUXl4THcKLS0tIFpSWkIwdHVFb1hZeWZtbDVTaW5O
            cGxUN1d2Vi9nMDB0UXdxckFEVi9rWFUKrO7roh4OXIC/u7mwtXpZ396o+EOBGT95
            TpKdj+p38qn2M3x9VkdKCkLV17Rl7UVXOczIENA+5FIeuuE4vajNrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:45:27Z"
    mac: ENC[AES256_GCM,data:r0xfQWX6CG2g1uygUiEHuziD5Y37DUEly0s1QnsBsitP2O46cF6GwVubrVxaudkoYEVE8cnB/E/+tHVvH+i0OOWvIYol8Cf/FIk6cRYBOUa+Louzbxc84KbQYOTeU4WbmrjSPBYjjLlHkBOubC33ZG3noVAeV0wL/3UCyXzJJ+U=,iv:R5cKVqVZR006VD99tRIkDOnZl8aszMHLxX6b0TZ20JE=,tag:fR+z7AH02H5Z4w22nkuEDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
