---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    fullnameOverride: pushgateway
    ingress:
      enabled: true
      className: traefik
      path: /
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
      hosts:
        - pushgateway.${SECRET_DOMAIN}
      tls:
        - hosts:
            - pushgateway.${SECRET_DOMAIN}
          secretName: pushgateway-tls
    serviceMonitor:
      enabled: true
      namespace: monitoring
