# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:mLH4BeJjfBiEKoCyXpPLeD4KvkGgeS8GyIGNaN+VYcPCME//ZETC84gYcViSj1lXu5Z9g7ahfFmERL84bmhgmBPLFHp+cIHlMBeY6dWV3ur25eq9SofD92r0e2XtXaH64JHTLMAhTk8YWa28mMBqMGFKS4FIv46EtnxbdkAJvi1CkmqmdNs1AAuGtc96ZVEFXE1573LxQFCrIw3OIbkpaVVLarvFO4ZLKSyza/itHzojwfRsx0T0jWajaA0xsP3HioHXjj/6UPrSRv/+AbBLsbWZLmlAzaVbPN0rte8=,iv:EkbS7NPkCkOR1trjeP8CmCiRhaZjA5svMxKDPoBo2l4=,tag:RoAKbKGnIJxw6m+rx7mTag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER2o5OUZjSy81OCtwSjFQ
            KzlSSnZ5Y0M2NzQwVjlscDJwcjJUMC9hUkVzCjN2UVVBSDMvcS96Mm1wdXE5aGZp
            K2dOWWdrT2hMTWZQL2RhbUdxb0FQV0kKLS0tIG5BL3ZwMk5BYUx0aHp3a2V4OXIz
            WTJiZVhkN01qZUhtL21nU3gxSlU3WTQKbJmudtxoSD6Fr5dIbH4itV1dw5RDpw3q
            yYROrNWCcZn9DocTy2nZ9Wk7BYTRBEJeYSR+C8OvVXmO3FZRRoS2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T16:22:11Z"
    mac: ENC[AES256_GCM,data:QgQSN7BCCOOaCusf2K4YNiZzIoiVeuK3GEJwHXujaWPwn8zE8jnwSdoPhin+uAzVyxDpA6rpTCZw6ucluwGIFIPEqKowQLjDvmbm3dUkLXsxQFa/eDhaBykeZpqvLDDPJ3bvEeubklrVPdyeWkhmthMrFSrjyZYvgUuOHJYtF7Y=,iv:57bHQqyW3P8ZqTWOAiu3pwO5fxVxHGNTQI1oQ4vJRnw=,tag:3colm3ohTH2Bx05z/GGnOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
