name: Meta - Sync labels

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
