---
name: Schedule - Cloudflare Proxied Networks Update

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  CLOUDFLARE_PROXIED_NETWORKS_FILE: >-
    cluster/apps/networking/traefik/middlewares/cloudflare.yaml
jobs:
  cloudflare-proxied-networks-update:
    name: Cloudflare Proxied Networks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cloudflare Proxied Networks
        run: |
          sed -Ei '\|    - [a-f0-9]+(\.\|:)|d' ${CLOUDFLARE_PROXIED_NETWORKS_FILE} && \
          bash ./.github/scripts/cloudflare-proxied-networks.sh >> ${CLOUDFLARE_PROXIED_NETWORKS_FILE}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: github-action/update-cloudflare-proxied-networks
          delete-branch: true
          title: "chore(github-action): update cloudflare proxied networks"
          signoff: true
          commit-message: "chore(github-action): update cloudflare proxied networks"
          body: |
            Update cloudflare proxy networks configmap from https://www.cloudflare.com/ips/
          labels: |
            renovate/github-action
