apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system.yaml
  - cert-manager.yaml
  - goldilocks.yaml
  - harbor.yaml
  - keycloak.yaml
  - media.yaml
  - metallb-system.yaml
  - networking.yaml
