---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system.yaml
  - cert-manager.yaml
  - falco-system.yaml
  - goldilocks.yaml
  - kube-system.yaml
  - media.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - tools.yaml
  - tor.yaml
